const GAMES_2 = [
    { "id": 2001, "title": "Pac-Man", "rating": 4.7, "plays": 220000, "category": "Arcade", "thumb": "images/PacMan.png", "iframe": "https://freepacman.org/" },
    { "id": 2002, "title": "Space Invaders", "rating": 4.5, "plays": 145000, "category": "Arcade", "thumb": "images/SpaceInvaders.png", "iframe": "https://spaceinvaders.cc/" },
    { "id": 2003, "title": "Frogger", "rating": 4.4, "plays": 98000, "category": "Arcade", "thumb": "images/Frogger.png", "iframe": "https://games.crazygames.com/en_US/frogger-in-toy-town/index.html" },
    { "id": 2004, "title": "Asteroids", "rating": 4.3, "plays": 87000, "category": "Arcade", "thumb": "images/Asteroids.png", "iframe": "https://www.classicgamesarcade.com/game/21670/asteroids.html" },
    { "id": 2005, "title": "Galaga", "rating": 4.5, "plays": 112000, "category": "Arcade", "thumb": "images/Galaga.png", "iframe": "https://galaga.io/" },
    { "id": 2006, "title": "Breakout", "rating": 4.4, "plays": 103000, "category": "Arcade", "thumb": "images/Breakout.png", "iframe": "https://games.crazygames.com/en_US/breakout/index.html" },
    { "id": 2007, "title": "Donkey Kong", "rating": 4.5, "plays": 130000, "category": "Arcade", "thumb": "images/DonkeyKong.png", "iframe": "https://www.retrogames.cc/embed/18754-donkey-kong.html" },
    { "id": 2008, "title": "Street Fighter II", "rating": 4.6, "plays": 158000, "category": "Arcade", "thumb": "images/StreetFighterII.png", "iframe": "https://www.retrogames.cc/embed/17786-street-fighter-ii-the-world-warrior.html" },
    { "id": 2009, "title": "Mortal Kombat", "rating": 4.5, "plays": 142000, "category": "Arcade", "thumb": "images/MortalKombat.png", "iframe": "https://www.retrogames.cc/embed/17740-mortal-kombat.html" },
    { "id": 2010, "title": "Sonic the Hedgehog", "rating": 4.7, "plays": 175000, "category": "Arcade", "thumb": "images/Sonic.png", "iframe": "https://www.retrogames.cc/embed/18755-sonic-the-hedgehog.html" },
    { "id": 2011, "title": "Super Mario Bros", "rating": 4.8, "plays": 260000, "category": "Arcade", "thumb": "images/SuperMario.png", "iframe": "https://www.retrogames.cc/embed/18753-super-mario-bros.html" },
    { "id": 2012, "title": "Contra", "rating": 4.5, "plays": 119000, "category": "Arcade", "thumb": "images/Contra.png", "iframe": "https://www.retrogames.cc/embed/18756-contra.html" },
    { "id": 2013, "title": "Tetris Classic", "rating": 4.6, "plays": 190000, "category": "Arcade", "thumb": "images/TetrisClassic.png", "iframe": "https://www.retrogames.cc/embed/18757-tetris.html" },
    { "id": 2014, "title": "Duck Hunt", "rating": 4.4, "plays": 108000, "category": "Arcade", "thumb": "images/DuckHunt.png", "iframe": "https://www.retrogames.cc/embed/18758-duck-hunt.html" },
    { "id": 2015, "title": "Bomberman", "rating": 4.5, "plays": 127000, "category": "Arcade", "thumb": "images/Bomberman.png", "iframe": "https://www.retrogames.cc/embed/18759-bomberman.html" },
    { "id": 2016, "title": "Centipede", "rating": 4.2, "plays": 73000, "category": "Arcade", "thumb": "images/Centipede.png", "iframe": "https://games.crazygames.com/en_US/centipede/index.html" },
    { "id": 2017, "title": "Pong", "rating": 4.3, "plays": 95000, "category": "Arcade", "thumb": "images/Pong.png", "iframe": "https://playpager.com/embed/pong/index.html" },
    { "id": 2018, "title": "Brick Breaker", "rating": 4.3, "plays": 81000, "category": "Arcade", "thumb": "images/BrickBreaker.png", "iframe": "https://games.crazygames.com/en_US/brick-breaker/index.html" },
    { "id": 2019, "title": "Jetpack Joyride", "rating": 4.5, "plays": 136000, "category": "Arcade", "thumb": "images/JetpackJoyride.png", "iframe": "https://games.crazygames.com/en_US/jetpack-joyride/index.html" },
    { "id": 2020, "title": "Temple Run 2", "rating": 4.5, "plays": 148000, "category": "Arcade", "thumb": "images/TempleRun.png", "iframe": "https://games.crazygames.com/en_US/temple-run-2/index.html" },
    { "id": 2021, "title": "Subway Surfers", "rating": 4.6, "plays": 195000, "category": "Arcade", "thumb": "images/SubwaySurfers.png", "iframe": "https://games.crazygames.com/en_US/subway-surfers/index.html" },
    { "id": 2022, "title": "Flappy Bird", "rating": 4.4, "plays": 172000, "category": "Arcade", "thumb": "images/FlappyBird.png", "iframe": "https://flappybird.io/" },
    { "id": 2023, "title": "Doodle Jump", "rating": 4.4, "plays": 129000, "category": "Arcade", "thumb": "images/DoodleJump.png", "iframe": "https://doodlejump.io/" },
    { "id": 2024, "title": "Angry Birds", "rating": 4.5, "plays": 163000, "category": "Arcade", "thumb": "images/AngryBirds.png", "iframe": "https://games.crazygames.com/en_US/angry-birds/index.html" },
    { "id": 2025, "title": "Fruit Ninja", "rating": 4.4, "plays": 141000, "category": "Arcade", "thumb": "images/FruitNinja.png", "iframe": "https://games.crazygames.com/en_US/fruit-ninja/index.html" },
    { "id": 2026, "title": "Bounce Ball", "rating": 4.2, "plays": 68000, "category": "Arcade", "thumb": "images/BounceBall.png", "iframe": "https://games.crazygames.com/en_US/bounce-ball/index.html" },
    { "id": 2027, "title": "Rolling Sky", "rating": 4.3, "plays": 82000, "category": "Arcade", "thumb": "images/RollingSky.png", "iframe": "https://games.crazygames.com/en_US/rolling-sky/index.html" },
    { "id": 2028, "title": "Ninja Jump", "rating": 4.1, "plays": 54000, "category": "Arcade", "thumb": "images/NinjaJump.png", "iframe": "https://games.crazygames.com/en_US/ninja-jump/index.html" },
    { "id": 2029, "title": "Chicken Invaders", "rating": 4.3, "plays": 91000, "category": "Arcade", "thumb": "images/ChickenInvaders.png", "iframe": "https://games.crazygames.com/en_US/chicken-invaders/index.html" },
    { "id": 2030, "title": "Crazy Flips 3D", "rating": 4.2, "plays": 63000, "category": "Arcade", "thumb": "images/CrazyFlips3D.png", "iframe": "https://games.crazygames.com/en_US/crazy-flips-3d/index.html" },
    { "id": 2031, "title": "Gold Miner", "rating": 4.3, "plays": 97000, "category": "Arcade", "thumb": "images/GoldMiner.png", "iframe": "https://www.coolmathgames.com/0-gold-miner" },
    { "id": 2032, "title": "Burrito Bison", "rating": 4.4, "plays": 88000, "category": "Arcade", "thumb": "images/BurritoBison.png", "iframe": "https://www.coolmathgames.com/0-burrito-bison" },
    { "id": 2033, "title": "Learn to Fly 3", "rating": 4.4, "plays": 86000, "category": "Arcade", "thumb": "images/LearnToFly3.png", "iframe": "https://www.coolmathgames.com/0-learn-to-fly-3" },
    { "id": 2034, "title": "Driving Force", "rating": 4.1, "plays": 52000, "category": "Arcade", "thumb": "images/DrivingForce.png", "iframe": "https://games.crazygames.com/en_US/driving-force/index.html" },
    { "id": 2035, "title": "Crazy Roller 3D", "rating": 4.2, "plays": 61000, "category": "Arcade", "thumb": "images/CrazyRoller3D.png", "iframe": "https://games.crazygames.com/en_US/crazy-roller-3d/index.html" },
    { "id": 2036, "title": "Basketfall", "rating": 4.1, "plays": 47000, "category": "Arcade", "thumb": "images/Basketfall.png", "iframe": "https://games.crazygames.com/en_US/basketfall/index.html" },
    { "id": 2037, "title": "Pinball", "rating": 4.4, "plays": 105000, "category": "Arcade", "thumb": "images/Pinball.png", "iframe": "https://pinballgame.io/" },
    { "id": 2038, "title": "Pac-Man 256", "rating": 4.5, "plays": 118000, "category": "Arcade", "thumb": "images/PacMan256.png", "iframe": "https://games.crazygames.com/en_US/pac-man-256/index.html" },
    { "id": 2039, "title": "Retro Bowl", "rating": 4.6, "plays": 134000, "category": "Arcade", "thumb": "images/RetroBowl.png", "iframe": "https://retrobowl.me/" },
    { "id": 2040, "title": "Endless Lake", "rating": 4.0, "plays": 38000, "category": "Arcade", "thumb": "images/EndlessLake.png", "iframe": "https://games.crazygames.com/en_US/endless-lake/index.html" },
    { "id": 2041, "title": "Rider", "rating": 4.3, "plays": 79000, "category": "Arcade", "thumb": "images/Rider.png", "iframe": "https://games.crazygames.com/en_US/rider/index.html" },
    { "id": 2042, "title": "Sky Rider", "rating": 4.2, "plays": 58000, "category": "Arcade", "thumb": "images/SkyRider.png", "iframe": "https://games.crazygames.com/en_US/sky-rider/index.html" },
    { "id": 2043, "title": "Hovercraft", "rating": 4.1, "plays": 44000, "category": "Arcade", "thumb": "images/Hovercraft.png", "iframe": "https://games.crazygames.com/en_US/hovercraft/index.html" },
    { "id": 2044, "title": "Turbo Dismounting", "rating": 4.3, "plays": 72000, "category": "Arcade", "thumb": "images/TurboDismounting.png", "iframe": "https://games.crazygames.com/en_US/turbo-dismounting/index.html" },
    { "id": 2045, "title": "Knife Hit", "rating": 4.4, "plays": 96000, "category": "Arcade", "thumb": "images/KnifeHit.png", "iframe": "https://games.crazygames.com/en_US/knife-hit/index.html" },
    { "id": 2046, "title": "Knife Smash", "rating": 4.2, "plays": 61000, "category": "Arcade", "thumb": "images/KnifeSmash.png", "iframe": "https://games.crazygames.com/en_US/knife-smash/index.html" },
    { "id": 2047, "title": "Crossy Road", "rating": 4.5, "plays": 143000, "category": "Arcade", "thumb": "images/CrossyRoad.png", "iframe": "https://crossyroad.com/" },
    { "id": 2048, "title": "Neon Bricks", "rating": 4.1, "plays": 43000, "category": "Arcade", "thumb": "images/NeonBricks.png", "iframe": "https://games.crazygames.com/en_US/neon-bricks/index.html" },
    { "id": 2049, "title": "Leap Day", "rating": 4.2, "plays": 56000, "category": "Arcade", "thumb": "images/LeapDay.png", "iframe": "https://games.crazygames.com/en_US/leap-day/index.html" },
    { "id": 2050, "title": "Basketball Stars", "rating": 4.4, "plays": 109000, "category": "Arcade", "thumb": "images/BasketballStars.png", "iframe": "https://games.crazygames.com/en_US/basketball-stars/index.html" },
    { "id": 2051, "title": "8 Ball Pool", "rating": 4.6, "plays": 187000, "category": "Arcade", "thumb": "images/8BallPool.png", "iframe": "https://www.miniclip.com/games/8-ball-pool-multiplayer/" },
    { "id": 2052, "title": "Baseball Boy", "rating": 4.2, "plays": 64000, "category": "Arcade", "thumb": "images/BaseballBoy.png", "iframe": "https://games.crazygames.com/en_US/baseball-boy/index.html" },
    { "id": 2053, "title": "Penalty Shooters 2", "rating": 4.3, "plays": 83000, "category": "Arcade", "thumb": "images/PenaltyShooters2.png", "iframe": "https://games.crazygames.com/en_US/penalty-shooters-2/index.html" },
    { "id": 2054, "title": "Archery World Tour", "rating": 4.2, "plays": 57000, "category": "Arcade", "thumb": "images/ArcheryWorldTour.png", "iframe": "https://games.crazygames.com/en_US/archery-world-tour/index.html" },
    { "id": 2055, "title": "Parkour Race", "rating": 4.4, "plays": 92000, "category": "Arcade", "thumb": "images/ParkourRace.png", "iframe": "https://games.crazygames.com/en_US/parkour-race/index.html" },
    { "id": 2056, "title": "Shortcut Run", "rating": 4.3, "plays": 78000, "category": "Arcade", "thumb": "images/ShortcutRun.png", "iframe": "https://games.crazygames.com/en_US/shortcut-run/index.html" },
    { "id": 2057, "title": "Count Masters", "rating": 4.2, "plays": 67000, "category": "Arcade", "thumb": "images/CountMasters.png", "iframe": "https://games.crazygames.com/en_US/count-masters/index.html" },
    { "id": 2058, "title": "Fall Beans", "rating": 4.4, "plays": 101000, "category": "Arcade", "thumb": "images/FallBeans.png", "iframe": "https://games.crazygames.com/en_US/fall-beans/index.html" },
    { "id": 2059, "title": "Stumble Guys", "rating": 4.5, "plays": 126000, "category": "Arcade", "thumb": "images/StumbleGuys.png", "iframe": "https://games.crazygames.com/en_US/stumble-guys/index.html" },
    { "id": 2060, "title": "Crowd City", "rating": 4.3, "plays": 85000, "category": "Arcade", "thumb": "images/CrowdCity.png", "iframe": "https://games.crazygames.com/en_US/crowd-city/index.html" },
    { "id": 2061, "title": "High Heels", "rating": 4.1, "plays": 59000, "category": "Arcade", "thumb": "images/HighHeels.png", "iframe": "https://games.crazygames.com/en_US/high-heels/index.html" },
    { "id": 2062, "title": "Sword Master", "rating": 4.2, "plays": 53000, "category": "Arcade", "thumb": "images/SwordMaster.png", "iframe": "https://games.crazygames.com/en_US/sword-master/index.html" },
    { "id": 2063, "title": "Roller Ball 6", "rating": 4.2, "plays": 62000, "category": "Arcade", "thumb": "images/RollerBall.png", "iframe": "https://games.crazygames.com/en_US/roller-ball-6/index.html" },
    { "id": 2064, "title": "Stack Jump", "rating": 4.1, "plays": 48000, "category": "Arcade", "thumb": "images/StackJump.png", "iframe": "https://games.crazygames.com/en_US/stack-jump/index.html" },
    { "id": 2065, "title": "Arrow Fest", "rating": 4.3, "plays": 74000, "category": "Arcade", "thumb": "images/ArrowFest.png", "iframe": "https://games.crazygames.com/en_US/arrow-fest/index.html" },
    { "id": 2066, "title": "Wobble Man", "rating": 4.0, "plays": 36000, "category": "Arcade", "thumb": "images/WobbleMan.png", "iframe": "https://games.crazygames.com/en_US/wobble-man/index.html" },
    { "id": 2067, "title": "Fun Race 3D", "rating": 4.3, "plays": 80000, "category": "Arcade", "thumb": "images/FunRace3D.png", "iframe": "https://games.crazygames.com/en_US/fun-race-3d/index.html" },
    { "id": 2068, "title": "Super Fowlst", "rating": 4.2, "plays": 55000, "category": "Arcade", "thumb": "images/SuperFowlst.png", "iframe": "https://games.crazygames.com/en_US/super-fowlst/index.html" },
    { "id": 2069, "title": "Neon Jump", "rating": 4.1, "plays": 42000, "category": "Arcade", "thumb": "images/NeonJump.png", "iframe": "https://games.crazygames.com/en_US/neon-jump/index.html" },
    { "id": 2070, "title": "Bridge Race", "rating": 4.3, "plays": 76000, "category": "Arcade", "thumb": "images/BridgeRace.png", "iframe": "https://games.crazygames.com/en_US/bridge-race/index.html" },
    { "id": 2071, "title": "Vex 6", "rating": 4.5, "plays": 111000, "category": "Arcade", "thumb": "images/Vex6.png", "iframe": "https://www.coolmathgames.com/0-vex-6" },
    { "id": 2072, "title": "Vex 7", "rating": 4.5, "plays": 107000, "category": "Arcade", "thumb": "images/Vex7.png", "iframe": "https://www.coolmathgames.com/0-vex-7" },
    { "id": 2073, "title": "OvO", "rating": 4.5, "plays": 99000, "category": "Arcade", "thumb": "images/OvO.png", "iframe": "https://www.coolmathgames.com/0-ovo" },
    { "id": 2074, "title": "Baldi's Basics", "rating": 4.1, "plays": 50000, "category": "Arcade", "thumb": "images/BaldisBasics.png", "iframe": "https://games.crazygames.com/en_US/baldis-basics/index.html" },
    { "id": 2075, "title": "Merge Round Racers", "rating": 4.1, "plays": 45000, "category": "Arcade", "thumb": "images/MergeRoundRacers.png", "iframe": "https://games.crazygames.com/en_US/merge-round-racers/index.html" },
    { "id": 2076, "title": "Ragdoll Hit", "rating": 4.2, "plays": 63000, "category": "Arcade", "thumb": "images/RagdollHit.png", "iframe": "https://games.crazygames.com/en_US/ragdoll-hit/index.html" },
    { "id": 2077, "title": "Clown Games", "rating": 4.0, "plays": 33000, "category": "Arcade", "thumb": "images/ClownGames.png", "iframe": "https://games.crazygames.com/en_US/clown-games/index.html" },
    { "id": 2078, "title": "Stick Merge", "rating": 4.2, "plays": 57000, "category": "Arcade", "thumb": "images/StickMerge.png", "iframe": "https://games.crazygames.com/en_US/stick-merge/index.html" },
    { "id": 2079, "title": "Eggy Car", "rating": 4.4, "plays": 88000, "category": "Arcade", "thumb": "images/EggyCar.png", "iframe": "https://games.crazygames.com/en_US/eggy-car/index.html" },
    { "id": 2080, "title": "Bouncing Ball", "rating": 4.1, "plays": 46000, "category": "Arcade", "thumb": "images/BouncingBall.png", "iframe": "https://games.crazygames.com/en_US/bouncing-ball/index.html" }
];
