const GAMES_ARCADE = [

    { "id": 9001, "title": "Color Road", "rating": 4.5, "plays": 49863, "category": "Arcade", "thumb": "images/Arcade/ColorRoad.png", "iframe": "https://www.madkidgames.com/games/color-road/" },
    { "id": 9002, "title": "Cat Runner: Decorate Home", "rating": 4.7, "plays": 32328, "category": "Arcade", "thumb": "images/Arcade/CatRunnerDecorateHome.png", "iframe": "https://www.madkidgames.com/games/cat-runner-decorate-home/?v=20260309113438" },
    { "id": 9003, "title": "Subway Princess Runner", "rating": 4.6, "plays": 60398, "category": "Arcade", "thumb": "images/Arcade/SubwayPrincessRunner.png", "iframe": "https://www.madkidgames.com/games/subway-princess-runner/?v=20260308172509" },
    { "id": 9004, "title": "Car Eats Car 3 Survival Racing", "rating": 4.3, "plays": 94205, "category": "Arcade", "thumb": "images/Arcade/CarEatsCar3SurvivalRacing.png", "iframe": "https://www.madkidgames.com/games/car-eats-car-3-survival-racing/" },
    { "id": 9005, "title": "Epic Skater 2", "rating": 4.8, "plays": 60609, "category": "Arcade", "thumb": "images/Arcade/EpicSkater2.png", "iframe": "https://www.madkidgames.com/games/epic-skater-2/?v=20260217101534" },
    { "id": 9006, "title": "Ghost Pop!", "rating": 4.7, "plays": 97012, "category": "Arcade", "thumb": "images/Arcade/GhostPop.png", "iframe": "https://www.madkidgames.com/games/ghost-pop/" },
    { "id": 9007, "title": "Fishy Bits 2", "rating": 4.2, "plays": 122278, "category": "Arcade", "thumb": "images/Arcade/FishyBits2.png", "iframe": "https://www.madkidgames.com/games/fishy-bits-2/" },
    { "id": 9008, "title": "Drift It!", "rating": 4.8, "plays": 92963, "category": "Arcade", "thumb": "images/Arcade/DriftIt.png", "iframe": "https://www.madkidgames.com/games/drift-it/" },
    { "id": 9009, "title": "Tennis Bits", "rating": 4.7, "plays": 69590, "category": "Arcade", "thumb": "images/Arcade/TennisBits.png", "iframe": "https://www.madkidgames.com/games/tennis-bits/" },
    { "id": 9010, "title": "Survival Island Idle Game", "rating": 4.1, "plays": 75623, "category": "Arcade", "thumb": "images/Arcade/SurvivalIslandIdleGame.png", "iframe": "https://www.madkidgames.com/games/survival-island-idle-game/?v=20260124130024" },
    { "id": 9011, "title": "Slope Down: First Trip", "rating": 4.6, "plays": 107196, "category": "Arcade", "thumb": "images/Arcade/SlopeDownFirstTrip.png", "iframe": "https://www.madkidgames.com/games/slope-down-first-trip/" },
    { "id": 9012, "title": "MMX Hill Dash 2 – Race Offroad", "rating": 4.1, "plays": 42866, "category": "Arcade", "thumb": "images/Arcade/MMXHillDash2RaceOffroad.png", "iframe": "https://www.madkidgames.com/games/mmx-hill-dash-2-race-offroad/?v=20260123223928" },
    { "id": 9013, "title": "Car Eats Car – Apocalypse Race", "rating": 4.0, "plays": 118615, "category": "Arcade", "thumb": "images/Arcade/CarEatsCarApocalypseRace.png", "iframe": "https://www.madkidgames.com/games/car-eats-car-apocalypse-race/?v=20260224151130" },
    { "id": 9014, "title": "Drive or Die: Zombie Apocalypse", "rating": 4.8, "plays": 124025, "category": "Arcade", "thumb": "images/Arcade/DriveorDieZombieApocalypse.png", "iframe": "https://www.madkidgames.com/games/drive-or-die-zombie-apocalypse/" },
    { "id": 9015, "title": "Police Car Chase", "rating": 4.5, "plays": 101454, "category": "Arcade", "thumb": "images/Arcade/PoliceCarChase.png", "iframe": "https://www.madkidgames.com/games/police-car-chase/?v=20250906120612" },


    { "id": 2001, "title": "Pac-Man", "rating": 4.7, "plays": 220000, "category": "Arcade", "thumb": "images/Arcade/PacMan.png", "iframe": "https://freepacman.org/" },
    { "id": 2079, "title": "Eggy Car", "rating": 4.4, "plays": 88000, "category": "Arcade", "thumb": "images/Arcade/EggyCar.png", "iframe": "https://games.crazygames.com/en_US/eggy-car/index.html" },
    { "id": 2004, "title": "Asteroids", "rating": 4.3, "plays": 87000, "category": "Arcade", "thumb": "images/Arcade/Asteroids.png", "iframe": "https://www.classicgamesarcade.com/game/21670/asteroids.html" },
    { "id": 2007, "title": "Donkey Kong", "rating": 4.5, "plays": 130000, "category": "Arcade", "thumb": "images/Arcade/DonkeyKong.png", "iframe": "https://www.retrogames.cc/embed/18754-donkey-kong.html" },
    { "id": 2008, "title": "Street Fighter II", "rating": 4.6, "plays": 158000, "category": "Arcade", "thumb": "images/Arcade/StreetFighterII.png", "iframe": "https://www.retrogames.cc/embed/17786-street-fighter-ii-the-world-warrior.html" },
    { "id": 2009, "title": "Mortal Kombat", "rating": 4.5, "plays": 142000, "category": "Arcade", "thumb": "images/Arcade/MortalKombat.png", "iframe": "https://www.retrogames.cc/embed/17740-mortal-kombat.html" },
    { "id": 2010, "title": "Sonic the Hedgehog", "rating": 4.7, "plays": 175000, "category": "Arcade", "thumb": "images/Arcade/Sonic.png", "iframe": "https://www.retrogames.cc/embed/18755-sonic-the-hedgehog.html" },
    { "id": 2011, "title": "Super Mario Bros", "rating": 4.8, "plays": 260000, "category": "Arcade", "thumb": "images/Arcade/SuperMario.png", "iframe": "https://www.retrogames.cc/embed/18753-super-mario-bros.html" },
    { "id": 2012, "title": "Contra", "rating": 4.5, "plays": 119000, "category": "Arcade", "thumb": "images/Arcade/Contra.png", "iframe": "https://www.retrogames.cc/embed/18756-contra.html" },
    { "id": 2013, "title": "Tetris Classic", "rating": 4.6, "plays": 190000, "category": "Arcade", "thumb": "images/Arcade/TetrisClassic.png", "iframe": "https://www.retrogames.cc/embed/18757-tetris.html" },
    { "id": 2014, "title": "Duck Hunt", "rating": 4.4, "plays": 108000, "category": "Arcade", "thumb": "images/Arcade/DuckHunt.png", "iframe": "https://www.retrogames.cc/embed/18758-duck-hunt.html" },
    { "id": 2015, "title": "Bomberman", "rating": 4.5, "plays": 127000, "category": "Arcade", "thumb": "images/Arcade/Bomberman.png", "iframe": "https://www.retrogames.cc/embed/18759-bomberman.html" },
    { "id": 2022, "title": "Flappy Bird", "rating": 4.4, "plays": 172000, "category": "Arcade", "thumb": "images/Arcade/FlappyBird.png", "iframe": "https://flappybird.io/" },
    { "id": 2023, "title": "Doodle Jump", "rating": 4.4, "plays": 129000, "category": "Arcade", "thumb": "images/Arcade/DoodleJump.png", "iframe": "https://doodlejump.io/" },
    { "id": 2017, "title": "Pong", "rating": 4.3, "plays": 95000, "category": "Arcade", "thumb": "images/Arcade/Pong.png", "iframe": "https://playpager.com/embed/pong/index.html" },
    { "id": 2030, "title": "Crazy Flips 3D", "rating": 4.2, "plays": 63000, "category": "Arcade", "thumb": "images/Arcade/CrazyFlips3D.png", "iframe": "https://games.crazygames.com/en_US/crazy-flips-3d/index.html" },
    { "id": 2039, "title": "Retro Bowl", "rating": 4.6, "plays": 134000, "category": "Arcade", "thumb": "images/Arcade/RetroBowl.png", "iframe": "https://retrobowl.me/" },
    { "id": 2044, "title": "Turbo Dismounting", "rating": 4.3, "plays": 72000, "category": "Arcade", "thumb": "images/Arcade/TurboDismounting.png", "iframe": "https://games.crazygames.com/en_US/turbo-dismounting/index.html" },
    { "id": 2047, "title": "Crossy Road", "rating": 4.5, "plays": 143000, "category": "Arcade", "thumb": "images/Arcade/CrossyRoad.png", "iframe": "https://crossyroad.com/" },
    { "id": 2053, "title": "Penalty Shooters 2", "rating": 4.3, "plays": 83000, "category": "Arcade", "thumb": "images/Arcade/PenaltyShooters2.png", "iframe": "https://games.crazygames.com/en_US/penalty-shooters-2/index.html" },
    { "id": 2054, "title": "Archery World Tour", "rating": 4.2, "plays": 57000, "category": "Arcade", "thumb": "images/Arcade/ArcheryWorldTour.png", "iframe": "https://games.crazygames.com/en_US/archery-world-tour/index.html" },
    { "id": 2031, "title": "Gold Miner", "rating": 4.3, "plays": 97000, "category": "Arcade", "thumb": "images/Arcade/GoldMiner.png", "iframe": "https://www.coolmathgames.com/0-gold-miner" },

];
