const GAMES_1 = [
    { "id": 1002, "title": "Bullet Force", "rating": 4.6, "plays": 95000, "category": "Action", "thumb": "images/BulletForce.png", "iframe": "https://games.crazygames.com/en_US/bullet-force-multiplayer/index.html" },
    { "id": 1003, "title": "Shell Shockers", "rating": 4.5, "plays": 87000, "category": "Action", "thumb": "images/ShellShockers.png", "iframe": "https://shellshock.io/" },
    { "id": 1004, "title": "Krunker.io", "rating": 4.7, "plays": 120000, "category": "Action", "thumb": "images/Krunker.png", "iframe": "https://krunker.io/" },
    { "id": 1005, "title": "Moomoo.io", "rating": 4.2, "plays": 62000, "category": "Action", "thumb": "images/Moomoo.png", "iframe": "https://moomoo.io/" },
    { "id": 1006, "title": "Surviv.io", "rating": 4.4, "plays": 75000, "category": "Action", "thumb": "images/Surviv.png", "iframe": "https://survev.io/" },
    { "id": 1007, "title": "Diep.io", "rating": 4.3, "plays": 68000, "category": "Action", "thumb": "images/Diep.png", "iframe": "https://diep.io/" },
    { "id": 1008, "title": "Agar.io", "rating": 4.2, "plays": 150000, "category": "Action", "thumb": "images/Agar.png", "iframe": "https://agar.io/" },
    { "id": 1009, "title": "Slither.io", "rating": 4.4, "plays": 140000, "category": "Action", "thumb": "images/Slither.png", "iframe": "https://slither.io/" },
    { "id": 1010, "title": "Zombs Royale", "rating": 4.5, "plays": 88000, "category": "Action", "thumb": "images/ZombsRoyale.png", "iframe": "https://zombsroyale.io/" },
    { "id": 1011, "title": "Warbrokers.io", "rating": 4.3, "plays": 45000, "category": "Action", "thumb": "images/Warbrokers.png", "iframe": "https://warbrokers.io/" },
    { "id": 1012, "title": "Battleground.io", "rating": 4.1, "plays": 39000, "category": "Action", "thumb": "images/Battleground.png", "iframe": "https://battleground.io/" },
    { "id": 1013, "title": "Paper.io 2", "rating": 4.4, "plays": 92000, "category": "Action", "thumb": "images/PaperIO2.png", "iframe": "https://paper-io.com/" },
    { "id": 1014, "title": "Gunblood", "rating": 4.2, "plays": 55000, "category": "Action", "thumb": "images/Gunblood.png", "iframe": "https://games.crazygames.com/en_US/gunblood/index.html" },
    { "id": 1015, "title": "Stickman Fighter Epic", "rating": 4.0, "plays": 41000, "category": "Action", "thumb": "images/StickmanFighter.png", "iframe": "https://html5.gamedistribution.com/rvvASXzFfCbWaGjgdkRz8A==/16c5ecce14034d65a83e8a29cbf2aaa9/" },
    { "id": 1016, "title": "Zombie Tsunami", "rating": 4.3, "plays": 67000, "category": "Action", "thumb": "images/ZombieTsunami.png", "iframe": "https://html5.gamedistribution.com/rvvASXzFfCbWaGjgdkRz8A==/zombie-tsunami/" },
    { "id": 1017, "title": "Pixel Warfare", "rating": 4.2, "plays": 48000, "category": "Action", "thumb": "images/PixelWarfare.png", "iframe": "https://games.crazygames.com/en_US/pixel-warfare/index.html" },
    { "id": 1018, "title": "Dead Zed", "rating": 4.1, "plays": 43000, "category": "Action", "thumb": "images/DeadZed.png", "iframe": "https://games.crazygames.com/en_US/dead-zed/index.html" },
    { "id": 1019, "title": "Strike Force Heroes", "rating": 4.5, "plays": 79000, "category": "Action", "thumb": "images/StrikeForceHeroes.png", "iframe": "https://www.strikeforceheroes.com/" },
    { "id": 1020, "title": "Lordz.io", "rating": 4.2, "plays": 36000, "category": "Action", "thumb": "images/Lordz.png", "iframe": "https://www.lordz.io/" },
    { "id": 1021, "title": "Wings.io", "rating": 4.3, "plays": 54000, "category": "Action", "thumb": "images/Wings.png", "iframe": "https://wings.io/" },
    { "id": 1022, "title": "Stabfish.io", "rating": 4.0, "plays": 31000, "category": "Action", "thumb": "images/Stabfish.png", "iframe": "https://stabfish.io/" },
    { "id": 1023, "title": "Superhot", "rating": 4.6, "plays": 83000, "category": "Action", "thumb": "images/Superhot.png", "iframe": "https://games.crazygames.com/en_US/superhot-prototype/index.html" },
    { "id": 1024, "title": "Venge.io", "rating": 4.5, "plays": 71000, "category": "Action", "thumb": "images/Venge.png", "iframe": "https://venge.io/" },
    { "id": 1025, "title": "Bruh.io", "rating": 4.1, "plays": 28000, "category": "Action", "thumb": "images/Bruh.png", "iframe": "https://bruh.io/" },
    { "id": 1026, "title": "Hordes.io", "rating": 4.4, "plays": 52000, "category": "Action", "thumb": "images/Hordes.png", "iframe": "https://hordes.io/" },
    { "id": 1027, "title": "Narwhal.io", "rating": 4.0, "plays": 27000, "category": "Action", "thumb": "images/Narwhal.png", "iframe": "https://narwhale.io/" },
    { "id": 1028, "title": "Hexar.io", "rating": 4.1, "plays": 33000, "category": "Action", "thumb": "images/Hexar.png", "iframe": "https://hexar.io/" },
    { "id": 1029, "title": "Gartic.io", "rating": 4.2, "plays": 60000, "category": "Action", "thumb": "images/Gartic.png", "iframe": "https://gartic.io/" },
    { "id": 1030, "title": "Crazy Shooters 2", "rating": 4.3, "plays": 46000, "category": "Action", "thumb": "images/CrazyShooters2.png", "iframe": "https://games.crazygames.com/en_US/crazy-shooters-2/index.html" },
    { "id": 1031, "title": "Combat Reloaded", "rating": 4.2, "plays": 59000, "category": "Action", "thumb": "images/CombatReloaded.png", "iframe": "https://games.crazygames.com/en_US/combat-reloaded/index.html" },
    { "id": 1032, "title": "Masked Forces", "rating": 4.0, "plays": 38000, "category": "Action", "thumb": "images/MaskedForces.png", "iframe": "https://games.crazygames.com/en_US/masked-forces/index.html" },
    { "id": 1033, "title": "Warscrap.io", "rating": 4.1, "plays": 29000, "category": "Action", "thumb": "images/Warscrap.png", "iframe": "https://warscrap.io/" },
    { "id": 1034, "title": "Worms Zone", "rating": 4.4, "plays": 85000, "category": "Action", "thumb": "images/WormsZone.png", "iframe": "https://wormszone.io/" },
    { "id": 1035, "title": "Lordz2.io", "rating": 4.2, "plays": 34000, "category": "Action", "thumb": "images/Lordz2.png", "iframe": "https://www.lordz2.io/" },
    { "id": 1036, "title": "Sploop.io", "rating": 4.1, "plays": 31000, "category": "Action", "thumb": "images/Sploop.png", "iframe": "https://sploop.io/" },
    { "id": 1037, "title": "Wolf in Space", "rating": 3.9, "plays": 22000, "category": "Action", "thumb": "images/WolfInSpace.png", "iframe": "https://idev.games/embed/wolf-in-space" },
    { "id": 1038, "title": "Vampire Land", "rating": 4.0, "plays": 25000, "category": "Action", "thumb": "images/VampireLand.png", "iframe": "https://idev.games/embed/vampire-land" },
    { "id": 1039, "title": "Zombie Tower Defense", "rating": 4.2, "plays": 44000, "category": "Action", "thumb": "images/ZombieTD.png", "iframe": "https://idev.games/embed/zombie-tower-defense-z-sector" },
    { "id": 1040, "title": "Horrible Platformer", "rating": 3.8, "plays": 19000, "category": "Action", "thumb": "images/HorriblePlatformer.png", "iframe": "https://idev.games/embed/horrible-platformer" },
    { "id": 1041, "title": "Ninjago Skybound", "rating": 4.1, "plays": 37000, "category": "Action", "thumb": "images/Ninjago.png", "iframe": "https://html5.gamedistribution.com/rvvASXzFfCbWaGjgdkRz8A==/ninjago/" },
    { "id": 1042, "title": "Bonk.io", "rating": 4.3, "plays": 57000, "category": "Action", "thumb": "images/Bonk.png", "iframe": "https://bonk.io/" },
    { "id": 1043, "title": "Defly.io", "rating": 4.2, "plays": 42000, "category": "Action", "thumb": "images/Defly.png", "iframe": "https://defly.io/" },
    { "id": 1044, "title": "Little Big Snake", "rating": 4.4, "plays": 78000, "category": "Action", "thumb": "images/LittleBigSnake.png", "iframe": "https://littlebigsnake.com/" },
    { "id": 1045, "title": "Arras.io", "rating": 4.3, "plays": 49000, "category": "Action", "thumb": "images/Arras.png", "iframe": "https://arras.io/" },
    { "id": 1046, "title": "Shooterz.io", "rating": 4.0, "plays": 26000, "category": "Action", "thumb": "images/Shooterz.png", "iframe": "https://shooterz.io/" },
    { "id": 1047, "title": "Skribbl.io", "rating": 4.5, "plays": 96000, "category": "Action", "thumb": "images/Skribbl.png", "iframe": "https://skribbl.io/" },
    { "id": 1048, "title": "Townscaper", "rating": 4.4, "plays": 63000, "category": "Action", "thumb": "images/Townscaper.png", "iframe": "https://oskarstalberg.com/Townscaper/" },
    { "id": 1049, "title": "Territorial.io", "rating": 4.4, "plays": 69000, "category": "Action", "thumb": "images/Territorial.png", "iframe": "https://territorial.io/" },
    { "id": 1050, "title": "Smash Karts", "rating": 4.6, "plays": 102000, "category": "Action", "thumb": "images/SmashKarts.png", "iframe": "https://smashkarts.io/" },
    { "id": 1051, "title": "Evowars.io", "rating": 4.3, "plays": 55000, "category": "Action", "thumb": "images/Evowars.png", "iframe": "https://evowars.io/" },
    { "id": 1052, "title": "Zombs.io", "rating": 4.2, "plays": 48000, "category": "Action", "thumb": "images/Zombs.png", "iframe": "https://zombs.io/" },
    { "id": 1053, "title": "Gats.io", "rating": 4.1, "plays": 34000, "category": "Action", "thumb": "images/Gats.png", "iframe": "https://gats.io/" },
    { "id": 1054, "title": "Gun Mayhem Redux", "rating": 4.2, "plays": 47000, "category": "Action", "thumb": "images/GunMayhemRedux.png", "iframe": "https://games.crazygames.com/en_US/gun-mayhem-redux/index.html" },
    { "id": 1055, "title": "Rooftop Snipers", "rating": 4.4, "plays": 73000, "category": "Action", "thumb": "images/RooftopSnipers.png", "iframe": "https://games.crazygames.com/en_US/rooftop-snipers/index.html" },
    { "id": 1056, "title": "Getaway Shootout", "rating": 4.3, "plays": 65000, "category": "Action", "thumb": "images/GetawayShootout.png", "iframe": "https://games.crazygames.com/en_US/getaway-shootout/index.html" },
    { "id": 1057, "title": "Ragdoll Archers", "rating": 4.3, "plays": 61000, "category": "Action", "thumb": "images/RagdollArchers.png", "iframe": "https://games.crazygames.com/en_US/ragdoll-archers/index.html" },
    { "id": 1058, "title": "Stickman Hook", "rating": 4.5, "plays": 89000, "category": "Action", "thumb": "images/StickmanHook.png", "iframe": "https://games.crazygames.com/en_US/stickman-hook/index.html" },
    { "id": 1059, "title": "Draw Climber", "rating": 4.1, "plays": 53000, "category": "Action", "thumb": "images/DrawClimber.png", "iframe": "https://games.crazygames.com/en_US/draw-climber/index.html" },
    { "id": 1060, "title": "Dino Game", "rating": 4.0, "plays": 200000, "category": "Action", "thumb": "images/DinoGame.png", "iframe": "https://chromedino.com/" },
    { "id": 1061, "title": "Slope", "rating": 4.5, "plays": 130000, "category": "Action", "thumb": "images/Slope.png", "iframe": "https://slope-game.com/" },
    { "id": 1062, "title": "Run 3", "rating": 4.5, "plays": 145000, "category": "Action", "thumb": "images/Run3.png", "iframe": "https://www.coolmathgames.com/0-run-3" },
    { "id": 1063, "title": "Fireboy and Watergirl", "rating": 4.6, "plays": 118000, "category": "Action", "thumb": "images/FireboyWatergirl.png", "iframe": "https://www.coolmathgames.com/0-fireboy-and-watergirl-in-the-forest-temple" },
    { "id": 1064, "title": "Drift Hunters", "rating": 4.6, "plays": 107000, "category": "Action", "thumb": "images/DriftHunters.png", "iframe": "https://games.crazygames.com/en_US/drift-hunters/index.html" },
    { "id": 1065, "title": "1v1.LOL", "rating": 4.5, "plays": 114000, "category": "Action", "thumb": "images/1v1LOL.png", "iframe": "https://1v1.lol/" },
    { "id": 1066, "title": "Crossy Road", "rating": 4.4, "plays": 99000, "category": "Action", "thumb": "images/CrossyRoad.png", "iframe": "https://crossyroad.com/" },
    { "id": 1067, "title": "Geometry Dash", "rating": 4.5, "plays": 122000, "category": "Action", "thumb": "images/GeometryDash.png", "iframe": "https://geometrydashgame.com/" },
    { "id": 1068, "title": "Stickman Warriors", "rating": 4.1, "plays": 44000, "category": "Action", "thumb": "images/StickmanWarriors.png", "iframe": "https://games.crazygames.com/en_US/stickman-warriors/index.html" },
    { "id": 1069, "title": "Bowman", "rating": 4.0, "plays": 39000, "category": "Action", "thumb": "images/Bowman.png", "iframe": "https://games.crazygames.com/en_US/bowman/index.html" },
    { "id": 1070, "title": "Sniper 3D", "rating": 4.3, "plays": 66000, "category": "Action", "thumb": "images/Sniper3D.png", "iframe": "https://games.crazygames.com/en_US/sniper-3d/index.html" },
    { "id": 1071, "title": "Tanki Online", "rating": 4.4, "plays": 81000, "category": "Action", "thumb": "images/TankiOnline.png", "iframe": "https://tankionline.com/" },
    { "id": 1072, "title": "Warzone.io", "rating": 4.1, "plays": 33000, "category": "Action", "thumb": "images/Warzone.png", "iframe": "https://warzone.io/" },
    { "id": 1073, "title": "Killer.io", "rating": 4.0, "plays": 29000, "category": "Action", "thumb": "images/Killer.png", "iframe": "https://killer.io/" },
    { "id": 1074, "title": "Ninja.io", "rating": 4.2, "plays": 41000, "category": "Action", "thumb": "images/Ninja.png", "iframe": "https://www.ninja.io/" },
    { "id": 1075, "title": "Pixel Gun Apocalypse 3", "rating": 4.1, "plays": 36000, "category": "Action", "thumb": "images/PixelGunApocalypse3.png", "iframe": "https://games.crazygames.com/en_US/pixel-gun-apocalypse-3/index.html" },
    { "id": 1076, "title": "Gun Fest", "rating": 4.0, "plays": 28000, "category": "Action", "thumb": "images/GunFest.png", "iframe": "https://games.crazygames.com/en_US/gun-fest/index.html" },
    { "id": 1077, "title": "Battle for the Galaxy", "rating": 4.2, "plays": 45000, "category": "Action", "thumb": "images/BattleGalaxy.png", "iframe": "https://games.crazygames.com/en_US/battle-for-the-galaxy/index.html" },
    { "id": 1078, "title": "Copter.io", "rating": 4.0, "plays": 30000, "category": "Action", "thumb": "images/Copter.png", "iframe": "https://copter.io/" },
    { "id": 1079, "title": "Zombs Royale 2", "rating": 4.3, "plays": 57000, "category": "Action", "thumb": "images/ZombsRoyale2.png", "iframe": "https://zombsroyale.io/" },
    { "id": 1080, "title": "Bullet Force Multiplayer", "rating": 4.5, "plays": 91000, "category": "Action", "thumb": "images/BulletForceMP.png", "iframe": "https://games.crazygames.com/en_US/bullet-force-multiplayer/index.html" }
];
