const GAMES_3 = [
    { "id": 3001, "title": "Zombs Royale", "rating": 4.6, "plays": 185000, "category": "Battle Royale", "thumb": "images/ZombsRoyale.png", "iframe": "https://zombsroyale.io/" },
    { "id": 3002, "title": "Surviv.io", "rating": 4.5, "plays": 162000, "category": "Battle Royale", "thumb": "images/Surviv.png", "iframe": "https://survev.io/" },
    { "id": 3003, "title": "1v1.LOL", "rating": 4.6, "plays": 210000, "category": "Battle Royale", "thumb": "images/1v1LOL.png", "iframe": "https://1v1.lol/" },
    { "id": 3004, "title": "Krunker.io", "rating": 4.7, "plays": 230000, "category": "Battle Royale", "thumb": "images/Krunker.png", "iframe": "https://krunker.io/" },
    { "id": 3005, "title": "Warbrokers.io", "rating": 4.3, "plays": 98000, "category": "Battle Royale", "thumb": "images/Warbrokers.png", "iframe": "https://warbrokers.io/" },
    { "id": 3006, "title": "Bullet Force", "rating": 4.5, "plays": 145000, "category": "Battle Royale", "thumb": "images/BulletForce.png", "iframe": "https://games.crazygames.com/en_US/bullet-force-multiplayer/index.html" },
    { "id": 3007, "title": "Shell Shockers", "rating": 4.5, "plays": 138000, "category": "Battle Royale", "thumb": "images/ShellShockers.png", "iframe": "https://shellshock.io/" },
    { "id": 3008, "title": "Venge.io", "rating": 4.5, "plays": 119000, "category": "Battle Royale", "thumb": "images/Venge.png", "iframe": "https://venge.io/" },
    { "id": 3009, "title": "Territorial.io", "rating": 4.4, "plays": 104000, "category": "Battle Royale", "thumb": "images/Territorial.png", "iframe": "https://territorial.io/" },
    { "id": 3010, "title": "Smash Karts", "rating": 4.6, "plays": 157000, "category": "Battle Royale", "thumb": "images/SmashKarts.png", "iframe": "https://smashkarts.io/" },
    { "id": 3011, "title": "Battleground.io", "rating": 4.2, "plays": 78000, "category": "Battle Royale", "thumb": "images/Battleground.png", "iframe": "https://battleground.io/" },
    { "id": 3012, "title": "Moomoo.io", "rating": 4.3, "plays": 112000, "category": "Battle Royale", "thumb": "images/Moomoo.png", "iframe": "https://moomoo.io/" },
    { "id": 3013, "title": "Zombs.io", "rating": 4.2, "plays": 87000, "category": "Battle Royale", "thumb": "images/Zombs.png", "iframe": "https://zombs.io/" },
    { "id": 3014, "title": "Diep.io", "rating": 4.3, "plays": 105000, "category": "Battle Royale", "thumb": "images/Diep.png", "iframe": "https://diep.io/" },
    { "id": 3015, "title": "Lordz.io", "rating": 4.2, "plays": 73000, "category": "Battle Royale", "thumb": "images/Lordz.png", "iframe": "https://www.lordz.io/" },
    { "id": 3016, "title": "Lordz2.io", "rating": 4.2, "plays": 69000, "category": "Battle Royale", "thumb": "images/Lordz2.png", "iframe": "https://www.lordz2.io/" },
    { "id": 3017, "title": "Wings.io", "rating": 4.3, "plays": 91000, "category": "Battle Royale", "thumb": "images/Wings.png", "iframe": "https://wings.io/" },
    { "id": 3018, "title": "Defly.io", "rating": 4.2, "plays": 82000, "category": "Battle Royale", "thumb": "images/Defly.png", "iframe": "https://defly.io/" },
    { "id": 3019, "title": "Arras.io", "rating": 4.3, "plays": 88000, "category": "Battle Royale", "thumb": "images/Arras.png", "iframe": "https://arras.io/" },
    { "id": 3020, "title": "Gats.io", "rating": 4.1, "plays": 64000, "category": "Battle Royale", "thumb": "images/Gats.png", "iframe": "https://gats.io/" },
    { "id": 3021, "title": "Bruh.io", "rating": 4.1, "plays": 58000, "category": "Battle Royale", "thumb": "images/Bruh.png", "iframe": "https://bruh.io/" },
    { "id": 3022, "title": "Evowars.io", "rating": 4.3, "plays": 96000, "category": "Battle Royale", "thumb": "images/Evowars.png", "iframe": "https://evowars.io/" },
    { "id": 3023, "title": "Narwhale.io", "rating": 4.0, "plays": 51000, "category": "Battle Royale", "thumb": "images/Narwhale.png", "iframe": "https://narwhale.io/" },
    { "id": 3024, "title": "Sploop.io", "rating": 4.1, "plays": 60000, "category": "Battle Royale", "thumb": "images/Sploop.png", "iframe": "https://sploop.io/" },
    { "id": 3025, "title": "Killer.io", "rating": 4.0, "plays": 54000, "category": "Battle Royale", "thumb": "images/Killer.png", "iframe": "https://killer.io/" },
    { "id": 3026, "title": "Ninja.io", "rating": 4.2, "plays": 75000, "category": "Battle Royale", "thumb": "images/Ninja.png", "iframe": "https://www.ninja.io/" },
    { "id": 3027, "title": "Bonk.io", "rating": 4.3, "plays": 93000, "category": "Battle Royale", "thumb": "images/Bonk.png", "iframe": "https://bonk.io/" },
    { "id": 3028, "title": "Hordes.io", "rating": 4.4, "plays": 86000, "category": "Battle Royale", "thumb": "images/Hordes.png", "iframe": "https://hordes.io/" },
    { "id": 3029, "title": "Warzone.io", "rating": 4.1, "plays": 62000, "category": "Battle Royale", "thumb": "images/Warzone.png", "iframe": "https://warzone.io/" },
    { "id": 3030, "title": "Warscrap.io", "rating": 4.1, "plays": 55000, "category": "Battle Royale", "thumb": "images/Warscrap.png", "iframe": "https://warscrap.io/" },
    { "id": 3031, "title": "Hexar.io", "rating": 4.1, "plays": 58000, "category": "Battle Royale", "thumb": "images/Hexar.png", "iframe": "https://hexar.io/" },
    { "id": 3032, "title": "Stabfish.io", "rating": 4.0, "plays": 49000, "category": "Battle Royale", "thumb": "images/Stabfish.png", "iframe": "https://stabfish.io/" },
    { "id": 3033, "title": "Copter.io", "rating": 4.0, "plays": 47000, "category": "Battle Royale", "thumb": "images/Copter.png", "iframe": "https://copter.io/" },
    { "id": 3034, "title": "Shooterz.io", "rating": 4.0, "plays": 45000, "category": "Battle Royale", "thumb": "images/Shooterz.png", "iframe": "https://shooterz.io/" },
    { "id": 3035, "title": "Hexanaut.io", "rating": 4.2, "plays": 71000, "category": "Battle Royale", "thumb": "images/Hexanaut.png", "iframe": "https://hexanaut.io/" },
    { "id": 3036, "title": "Combat Reloaded", "rating": 4.2, "plays": 84000, "category": "Battle Royale", "thumb": "images/CombatReloaded.png", "iframe": "https://games.crazygames.com/en_US/combat-reloaded/index.html" },
    { "id": 3037, "title": "Combat Reloaded 2", "rating": 4.3, "plays": 91000, "category": "Battle Royale", "thumb": "images/CombatReloaded2.png", "iframe": "https://games.crazygames.com/en_US/combat-reloaded-2/index.html" },
    { "id": 3038, "title": "Masked Forces", "rating": 4.0, "plays": 63000, "category": "Battle Royale", "thumb": "images/MaskedForces.png", "iframe": "https://games.crazygames.com/en_US/masked-forces/index.html" },
    { "id": 3039, "title": "Pixel Warfare", "rating": 4.2, "plays": 77000, "category": "Battle Royale", "thumb": "images/PixelWarfare.png", "iframe": "https://games.crazygames.com/en_US/pixel-warfare/index.html" },
    { "id": 3040, "title": "Crazy Shooters 2", "rating": 4.3, "plays": 80000, "category": "Battle Royale", "thumb": "images/CrazyShooters2.png", "iframe": "https://games.crazygames.com/en_US/crazy-shooters-2/index.html" },
    { "id": 3041, "title": "Pixel Gun Apocalypse 3", "rating": 4.1, "plays": 68000, "category": "Battle Royale", "thumb": "images/PixelGunApocalypse3.png", "iframe": "https://games.crazygames.com/en_US/pixel-gun-apocalypse-3/index.html" },
    { "id": 3042, "title": "Pixel Gun Apocalypse 5", "rating": 4.2, "plays": 72000, "category": "Battle Royale", "thumb": "images/PixelGunApocalypse5.png", "iframe": "https://games.crazygames.com/en_US/pixel-gun-apocalypse-5/index.html" },
    { "id": 3043, "title": "Rooftop Snipers", "rating": 4.4, "plays": 107000, "category": "Battle Royale", "thumb": "images/RooftopSnipers.png", "iframe": "https://games.crazygames.com/en_US/rooftop-snipers/index.html" },
    { "id": 3044, "title": "Getaway Shootout", "rating": 4.3, "plays": 99000, "category": "Battle Royale", "thumb": "images/GetawayShootout.png", "iframe": "https://games.crazygames.com/en_US/getaway-shootout/index.html" },
    { "id": 3045, "title": "Gun Mayhem Redux", "rating": 4.2, "plays": 81000, "category": "Battle Royale", "thumb": "images/GunMayhemRedux.png", "iframe": "https://games.crazygames.com/en_US/gun-mayhem-redux/index.html" },
    { "id": 3046, "title": "Gun Fest", "rating": 4.0, "plays": 52000, "category": "Battle Royale", "thumb": "images/GunFest.png", "iframe": "https://games.crazygames.com/en_US/gun-fest/index.html" },
    { "id": 3047, "title": "Sniper 3D", "rating": 4.3, "plays": 103000, "category": "Battle Royale", "thumb": "images/Sniper3D.png", "iframe": "https://games.crazygames.com/en_US/sniper-3d/index.html" },
    { "id": 3048, "title": "Dead Zed", "rating": 4.1, "plays": 67000, "category": "Battle Royale", "thumb": "images/DeadZed.png", "iframe": "https://games.crazygames.com/en_US/dead-zed/index.html" },
    { "id": 3049, "title": "Ragdoll Archers", "rating": 4.3, "plays": 95000, "category": "Battle Royale", "thumb": "images/RagdollArchers.png", "iframe": "https://games.crazygames.com/en_US/ragdoll-archers/index.html" },
    { "id": 3050, "title": "Bowman", "rating": 4.0, "plays": 61000, "category": "Battle Royale", "thumb": "images/Bowman.png", "iframe": "https://games.crazygames.com/en_US/bowman/index.html" },
    { "id": 3051, "title": "Battle for the Galaxy", "rating": 4.2, "plays": 74000, "category": "Battle Royale", "thumb": "images/BattleGalaxy.png", "iframe": "https://games.crazygames.com/en_US/battle-for-the-galaxy/index.html" },
    { "id": 3052, "title": "Strike Force Heroes", "rating": 4.5, "plays": 122000, "category": "Battle Royale", "thumb": "images/StrikeForceHeroes.png", "iframe": "https://www.strikeforceheroes.com/" },
    { "id": 3053, "title": "Tanki Online", "rating": 4.4, "plays": 118000, "category": "Battle Royale", "thumb": "images/TankiOnline.png", "iframe": "https://tankionline.com/" },
    { "id": 3054, "title": "Tank Trouble", "rating": 4.3, "plays": 97000, "category": "Battle Royale", "thumb": "images/TankTrouble.png", "iframe": "https://tanktrouble.com/" },
    { "id": 3055, "title": "Worms Zone", "rating": 4.4, "plays": 124000, "category": "Battle Royale", "thumb": "images/WormsZone.png", "iframe": "https://wormszone.io/" },
    { "id": 3056, "title": "Little Big Snake", "rating": 4.4, "plays": 113000, "category": "Battle Royale", "thumb": "images/LittleBigSnake.png", "iframe": "https://littlebigsnake.com/" },
    { "id": 3057, "title": "Agar.io", "rating": 4.3, "plays": 195000, "category": "Battle Royale", "thumb": "images/Agar.png", "iframe": "https://agar.io/" },
    { "id": 3058, "title": "Slither.io", "rating": 4.4, "plays": 188000, "category": "Battle Royale", "thumb": "images/Slither.png", "iframe": "https://slither.io/" },
    { "id": 3059, "title": "Paper.io 2", "rating": 4.4, "plays": 134000, "category": "Battle Royale", "thumb": "images/PaperIO2.png", "iframe": "https://paper-io.com/" },
    { "id": 3060, "title": "Superhot Prototype", "rating": 4.5, "plays": 126000, "category": "Battle Royale", "thumb": "images/Superhot.png", "iframe": "https://games.crazygames.com/en_US/superhot-prototype/index.html" },
    { "id": 3061, "title": "Masked Forces 3", "rating": 4.1, "plays": 59000, "category": "Battle Royale", "thumb": "images/MaskedForces3.png", "iframe": "https://games.crazygames.com/en_US/masked-forces-3/index.html" },
    { "id": 3062, "title": "Pixel Combat 2", "rating": 4.2, "plays": 76000, "category": "Battle Royale", "thumb": "images/PixelCombat2.png", "iframe": "https://games.crazygames.com/en_US/pixel-combat-2/index.html" },
    { "id": 3063, "title": "Forward Assault Remix", "rating": 4.3, "plays": 88000, "category": "Battle Royale", "thumb": "images/ForwardAssaultRemix.png", "iframe": "https://games.crazygames.com/en_US/forward-assault-remix/index.html" },
    { "id": 3064, "title": "Modern Ops", "rating": 4.4, "plays": 109000, "category": "Battle Royale", "thumb": "images/ModernOps.png", "iframe": "https://games.crazygames.com/en_US/modern-ops/index.html" },
    { "id": 3065, "title": "War Brokers Classic", "rating": 4.2, "plays": 71000, "category": "Battle Royale", "thumb": "images/WarBrokersClassic.png", "iframe": "https://games.crazygames.com/en_US/war-brokers/index.html" },
    { "id": 3066, "title": "Blocky Combat SWAT", "rating": 4.1, "plays": 63000, "category": "Battle Royale", "thumb": "images/BlockyCombatSWAT.png", "iframe": "https://games.crazygames.com/en_US/blocky-combat-swat/index.html" },
    { "id": 3067, "title": "Stickman Battle Fighter", "rating": 4.0, "plays": 54000, "category": "Battle Royale", "thumb": "images/StickmanBattleFighter.png", "iframe": "https://games.crazygames.com/en_US/stickman-battle-fighter/index.html" },
    { "id": 3068, "title": "Stickman Warriors", "rating": 4.1, "plays": 67000, "category": "Battle Royale", "thumb": "images/StickmanWarriors.png", "iframe": "https://games.crazygames.com/en_US/stickman-warriors/index.html" },
    { "id": 3069, "title": "City Siege Sniper", "rating": 4.1, "plays": 58000, "category": "Battle Royale", "thumb": "images/CitySiegeSniper.png", "iframe": "https://games.crazygames.com/en_US/city-siege-sniper/index.html" },
    { "id": 3070, "title": "Cyber Soldiers", "rating": 4.0, "plays": 47000, "category": "Battle Royale", "thumb": "images/CyberSoldiers.png", "iframe": "https://games.crazygames.com/en_US/cyber-soldiers/index.html" },
    { "id": 3071, "title": "Mad GunZ", "rating": 4.2, "plays": 79000, "category": "Battle Royale", "thumb": "images/MadGunZ.png", "iframe": "https://games.crazygames.com/en_US/mad-gunz/index.html" },
    { "id": 3072, "title": "Paintball Battle", "rating": 4.1, "plays": 55000, "category": "Battle Royale", "thumb": "images/PaintballBattle.png", "iframe": "https://games.crazygames.com/en_US/paintball-battle-royale/index.html" },
    { "id": 3073, "title": "Battle Royale in 3 Min", "rating": 4.0, "plays": 42000, "category": "Battle Royale", "thumb": "images/BattleRoyale3Min.png", "iframe": "https://games.crazygames.com/en_US/battle-royale-in-3-minutes/index.html" },
    { "id": 3074, "title": "Island Royale", "rating": 4.2, "plays": 66000, "category": "Battle Royale", "thumb": "images/IslandRoyale.png", "iframe": "https://games.crazygames.com/en_US/island-royale/index.html" },
    { "id": 3075, "title": "Crazy Pixel Apocalypse", "rating": 4.1, "plays": 57000, "category": "Battle Royale", "thumb": "images/CrazyPixelApocalypse.png", "iframe": "https://games.crazygames.com/en_US/crazy-pixel-apocalypse/index.html" },
    { "id": 3076, "title": "Egg Wars", "rating": 4.2, "plays": 73000, "category": "Battle Royale", "thumb": "images/EggWars.png", "iframe": "https://games.crazygames.com/en_US/egg-wars/index.html" },
    { "id": 3077, "title": "Mini Royale Nations", "rating": 4.4, "plays": 101000, "category": "Battle Royale", "thumb": "images/MiniRoyaleNations.png", "iframe": "https://miniroyale.io/" },
    { "id": 3078, "title": "Skullz.io", "rating": 4.0, "plays": 43000, "category": "Battle Royale", "thumb": "images/Skullz.png", "iframe": "https://skullz.io/" },
    { "id": 3079, "title": "Foes.io", "rating": 4.2, "plays": 69000, "category": "Battle Royale", "thumb": "images/Foes.png", "iframe": "https://foes.io/" },
    { "id": 3080, "title": "Kirka.io", "rating": 4.4, "plays": 115000, "category": "Battle Royale", "thumb": "images/Kirka.png", "iframe": "https://kirka.io/" }
];
