const GAMES_BATTLEROYALE = [
    { "id": 3054, "title": "Tank Trouble", "rating": 4.3, "plays": 97000, "category": "Battle Royale", "thumb": "images/BattleRoyale/TankTrouble.png", "iframe": "https://tanktrouble.com/" },
    { "id": 3055, "title": "Worms Zone", "rating": 4.4, "plays": 124000, "category": "Battle Royale", "thumb": "images/BattleRoyale/WormsZone.png", "iframe": "https://wormszone.io/" },
    { "id": 3056, "title": "Little Big Snake", "rating": 4.4, "plays": 113000, "category": "Battle Royale", "thumb": "images/BattleRoyale/LittleBigSnake.png", "iframe": "https://littlebigsnake.com/" },
    { "id": 3048, "title": "Dead Zed", "rating": 4.1, "plays": 67000, "category": "Battle Royale", "thumb": "images/BattleRoyale/DeadZed.png", "iframe": "https://games.crazygames.com/en_US/dead-zed/index.html" },
    { "id": 3049, "title": "Ragdoll Archers", "rating": 4.3, "plays": 95000, "category": "Battle Royale", "thumb": "images/BattleRoyale/RagdollArchers.png", "iframe": "https://games.crazygames.com/en_US/ragdoll-archers/index.html" },
    { "id": 3050, "title": "Bowman", "rating": 4.0, "plays": 61000, "category": "Battle Royale", "thumb": "images/BattleRoyale/Bowman.png", "iframe": "https://games.crazygames.com/en_US/bowman/index.html" },
    { "id": 3051, "title": "Battle for the Galaxy", "rating": 4.2, "plays": 74000, "category": "Battle Royale", "thumb": "images/BattleRoyale/BattleGalaxy.png", "iframe": "https://games.crazygames.com/en_US/battle-for-the-galaxy/index.html" },
    { "id": 3032, "title": "Stabfish.io", "rating": 4.0, "plays": 49000, "category": "Battle Royale", "thumb": "images/BattleRoyale/Stabfish.png", "iframe": "https://stabfish.io/" },
    { "id": 3033, "title": "Copter.io", "rating": 4.0, "plays": 47000, "category": "Battle Royale", "thumb": "images/BattleRoyale/Copter.png", "iframe": "https://copter.io/" },
    { "id": 3034, "title": "Shooterz.io", "rating": 4.0, "plays": 45000, "category": "Battle Royale", "thumb": "images/BattleRoyale/Shooterz.png", "iframe": "https://shooterz.io/" },
    { "id": 3035, "title": "Hexanaut.io", "rating": 4.2, "plays": 71000, "category": "Battle Royale", "thumb": "images/BattleRoyale/Hexanaut.png", "iframe": "https://hexanaut.io/" },
    { "id": 3027, "title": "Bonk.io", "rating": 4.3, "plays": 93000, "category": "Battle Royale", "thumb": "images/BattleRoyale/Bonk.png", "iframe": "https://bonk.io/" },
    { "id": 3024, "title": "Sploop.io", "rating": 4.1, "plays": 60000, "category": "Battle Royale", "thumb": "images/BattleRoyale/Sploop.png", "iframe": "https://sploop.io/" },
    { "id": 3012, "title": "Moomoo.io", "rating": 4.3, "plays": 112000, "category": "Battle Royale", "thumb": "images/BattleRoyale/Moomoo.png", "iframe": "https://moomoo.io/" },
    { "id": 3013, "title": "Zombs.io", "rating": 4.2, "plays": 87000, "category": "Battle Royale", "thumb": "images/BattleRoyale/Zombs.png", "iframe": "https://zombs.io/" },
    { "id": 3014, "title": "Diep.io", "rating": 4.3, "plays": 105000, "category": "Battle Royale", "thumb": "images/BattleRoyale/Diep.png", "iframe": "https://diep.io/" },
    { "id": 3015, "title": "Lordz.io", "rating": 4.2, "plays": 73000, "category": "Battle Royale", "thumb": "images/BattleRoyale/Lordz.png", "iframe": "https://www.lordz.io/" },
    { "id": 3016, "title": "Lordz2.io", "rating": 4.2, "plays": 69000, "category": "Battle Royale", "thumb": "images/BattleRoyale/Lordz2.png", "iframe": "https://www.lordz2.io/" },
    { "id": 3017, "title": "Wings.io", "rating": 4.3, "plays": 91000, "category": "Battle Royale", "thumb": "images/BattleRoyale/Wings.png", "iframe": "https://wings.io/" },
    { "id": 3018, "title": "Defly.io", "rating": 4.2, "plays": 82000, "category": "Battle Royale", "thumb": "images/BattleRoyale/Defly.png", "iframe": "https://defly.io/" },
    { "id": 3019, "title": "Arras.io", "rating": 4.3, "plays": 88000, "category": "Battle Royale", "thumb": "images/BattleRoyale/Arras.png", "iframe": "https://arras.io/" },
    { "id": 3020, "title": "Gats.io", "rating": 4.1, "plays": 64000, "category": "Battle Royale", "thumb": "images/BattleRoyale/Gats.png", "iframe": "https://gats.io/" },
    { "id": 3021, "title": "Bruh.io", "rating": 4.1, "plays": 58000, "category": "Battle Royale", "thumb": "images/BattleRoyale/Bruh.png", "iframe": "https://bruh.io/" },
    { "id": 3022, "title": "Evowars.io", "rating": 4.3, "plays": 96000, "category": "Battle Royale", "thumb": "images/BattleRoyale/Evowars.png", "iframe": "https://evowars.io/" },
    { "id": 3007, "title": "Shell Shockers", "rating": 4.5, "plays": 138000, "category": "Battle Royale", "thumb": "images/BattleRoyale/ShellShockers.png", "iframe": "https://shellshock.io/" },
    { "id": 3008, "title": "Venge.io", "rating": 4.5, "plays": 119000, "category": "Battle Royale", "thumb": "images/BattleRoyale/Venge.png", "iframe": "https://venge.io/" },
    { "id": 3009, "title": "Territorial.io", "rating": 4.4, "plays": 104000, "category": "Battle Royale", "thumb": "images/BattleRoyale/Territorial.png", "iframe": "https://territorial.io/" },
    { "id": 3010, "title": "Smash Karts", "rating": 4.6, "plays": 157000, "category": "Battle Royale", "thumb": "images/BattleRoyale/SmashKarts.png", "iframe": "https://smashkarts.io/" },
    { "id": 3004, "title": "Krunker.io", "rating": 4.7, "plays": 230000, "category": "Battle Royale", "thumb": "images/BattleRoyale/Krunker.png", "iframe": "https://krunker.io/" },
    { "id": 3005, "title": "Warbrokers.io", "rating": 4.3, "plays": 98000, "category": "Battle Royale", "thumb": "images/BattleRoyale/Warbrokers.png", "iframe": "https://warbrokers.io/" },

];
