const GAMES_PUZZLE = [
    { "id": 8, "title": "Little Alchemy 2", "rating": 4.8, "plays": 58000, "category": "Puzzle", "thumb": "images/Puzzle/LittleAlchemy2.png", "iframe": "https://littlealchemy2.com/" },
    { "id": 4010, "title": "Solitaire", "rating": 4.6, "plays": 195000, "category": "Puzzle", "thumb": "images/Puzzle/Solitaire.png", "iframe": "https://playpager.com/embed/solitaire/index.html" },
    { "id": 4077, "title": "Lights Off", "rating": 4.0, "plays": 34000, "category": "Puzzle", "thumb": "images/Puzzle/LightsOff.png", "iframe": "https://www.mathsisfun.com/games/lightsout.html" },
    { "id": 4078, "title": "Simon Says", "rating": 4.1, "plays": 43000, "category": "Puzzle", "thumb": "images/Puzzle/SimonSays.png", "iframe": "https://www.mathsisfun.com/games/simon-says.html" },
    { "id": 4079, "title": "Hexanaut.io", "rating": 4.3, "plays": 57000, "category": "Puzzle", "thumb": "images/Puzzle/Hexanaut.png", "iframe": "https://hexanaut.io/" },
    { "id": 4002, "title": "Wordle", "rating": 4.7, "plays": 250000, "category": "Puzzle", "thumb": "images/Puzzle/Wordle.png", "iframe": "https://wordlegame.org/" },
    { "id": 4003, "title": "Sudoku", "rating": 4.5, "plays": 160000, "category": "Puzzle", "thumb": "images/Puzzle/Sudoku.png", "iframe": "https://playpager.com/embed/sudoku/index.html" },
    { "id": 4004, "title": "Chess", "rating": 4.8, "plays": 210000, "category": "Puzzle", "thumb": "images/Puzzle/Chess.png", "iframe": "https://playpager.com/embed/chess/index.html" },
    { "id": 4005, "title": "Mahjong", "rating": 4.5, "plays": 130000, "category": "Puzzle", "thumb": "images/Puzzle/Mahjong.png", "iframe": "https://www.mahjong.io/" },
    { "id": 4006, "title": "Checkers", "rating": 4.3, "plays": 85000, "category": "Puzzle", "thumb": "images/Puzzle/Checkers.png", "iframe": "https://playpager.com/embed/checkers/index.html" },
    { "id": 4007, "title": "Reversi Othello", "rating": 4.2, "plays": 56000, "category": "Puzzle", "thumb": "images/Puzzle/Reversi.png", "iframe": "https://playpager.com/embed/reversi/index.html" },
    { "id": 4008, "title": "Falling Cubes", "rating": 4.1, "plays": 47000, "category": "Puzzle", "thumb": "images/Puzzle/FallingCubes.png", "iframe": "https://playpager.com/embed/cubes/index.html" },
    { "id": 4009, "title": "Word Puzzle", "rating": 4.2, "plays": 63000, "category": "Puzzle", "thumb": "images/Puzzle/WordPuzzle.png", "iframe": "https://playpager.com/embed/wordpuzzle/index.html" },
    { "id": 4012, "title": "Tetris", "rating": 4.7, "plays": 230000, "category": "Puzzle", "thumb": "images/Puzzle/Tetris.png", "iframe": "https://tetris.com/play-tetris" },
    { "id": 4014, "title": "Bubble Shooter", "rating": 4.5, "plays": 148000, "category": "Puzzle", "thumb": "images/Puzzle/BubbleShooter.png", "iframe": "https://www.bubbleshooter.net/" },
    { "id": 4016, "title": "Domino Tiler", "rating": 4.0, "plays": 32000, "category": "Puzzle", "thumb": "images/Puzzle/DominoTiler.png", "iframe": "https://idev.games/embed/domino-tiler" },
    { "id": 4017, "title": "Arcanoid Aquarium", "rating": 4.1, "plays": 38000, "category": "Puzzle", "thumb": "images/Puzzle/ArcanoidAquarium.png", "iframe": "https://idev.games/embed/arcanoid-acuarium" },
    { "id": 4018, "title": "Tower of Hanoi", "rating": 4.2, "plays": 44000, "category": "Puzzle", "thumb": "images/Puzzle/TowerOfHanoi.png", "iframe": "https://www.mathsisfun.com/games/towerofhanoi.html" },
    { "id": 4019, "title": "Minesweeper", "rating": 4.4, "plays": 122000, "category": "Puzzle", "thumb": "images/Puzzle/Minesweeper.png", "iframe": "https://minesweeper.online/" },
    { "id": 4021, "title": "Merge Fruits", "rating": 4.3, "plays": 76000, "category": "Puzzle", "thumb": "images/Puzzle/MergeFruits.png", "iframe": "https://games.crazygames.com/en_US/merge-fruits/index.html" },
    { "id": 4030, "title": "Helix Jump", "rating": 4.5, "plays": 115000, "category": "Puzzle", "thumb": "images/Puzzle/HelixJump.png", "iframe": "https://games.crazygames.com/en_US/helix-jump/index.html" },
    { "id": 4050, "title": "Crossword Puzzle", "rating": 4.4, "plays": 80000, "category": "Puzzle", "thumb": "images/Puzzle/CrosswordPuzzle.png", "iframe": "https://www.crosswordpuzzles.com/" },
    { "id": 4051, "title": "Good Sudoku", "rating": 4.5, "plays": 93000, "category": "Puzzle", "thumb": "images/Puzzle/GoodSudoku.png", "iframe": "https://www.websudoku.com/" },
    { "id": 4046, "title": "Picross", "rating": 4.3, "plays": 52000, "category": "Puzzle", "thumb": "images/Puzzle/Picross.png", "iframe": "https://www.puzzle-nonograms.com/" },
    { "id": 4056, "title": "Emoji Puzzle", "rating": 4.3, "plays": 68000, "category": "Puzzle", "thumb": "images/Puzzle/EmojiPuzzle.png", "iframe": "https://games.crazygames.com/en_US/emoji-puzzle/index.html" },
    { "id": 4057, "title": "Quordle", "rating": 4.4, "plays": 77000, "category": "Puzzle", "thumb": "images/Puzzle/Quordle.png", "iframe": "https://quordle.com/" },
    { "id": 4064, "title": "Numberle", "rating": 4.2, "plays": 51000, "category": "Puzzle", "thumb": "images/Puzzle/Numberle.png", "iframe": "https://numberle.org/" },
    { "id": 4072, "title": "Words of Wonders", "rating": 4.3, "plays": 69000, "category": "Puzzle", "thumb": "images/Puzzle/WordsOfWonders.png", "iframe": "https://games.crazygames.com/en_US/words-of-wonders/index.html" },


    // { "id": 4058, "title": "Scratch & Guess Logos", "rating": 4.1, "plays": 33000, "category": "Puzzle", "thumb": "images/Puzzle/ScratchGuess.png", "iframe": "https://games.crazygames.com/en_US/scratch-guess-logos/index.html" },
    // { "id": 4059, "title": "Tiles Hop", "rating": 4.3, "plays": 72000, "category": "Puzzle", "thumb": "images/Puzzle/TilesHop.png", "iframe": "https://games.crazygames.com/en_US/tiles-hop/index.html" },
    // { "id": 4060, "title": "Music Tiles", "rating": 4.4, "plays": 86000, "category": "Puzzle", "thumb": "images/Puzzle/MusicTiles.png", "iframe": "https://games.crazygames.com/en_US/music-tiles/index.html" },
    // { "id": 4061, "title": "Woodoku", "rating": 4.5, "plays": 101000, "category": "Puzzle", "thumb": "images/Puzzle/Woodoku.png", "iframe": "https://games.crazygames.com/en_US/woodoku/index.html" },
    // { "id": 4062, "title": "Cuboid", "rating": 4.0, "plays": 29000, "category": "Puzzle", "thumb": "images/Puzzle/Cuboid.png", "iframe": "https://games.crazygames.com/en_US/cuboid/index.html" },
    // { "id": 4063, "title": "Merge Arena", "rating": 4.1, "plays": 43000, "category": "Puzzle", "thumb": "images/Puzzle/MergeArena.png", "iframe": "https://games.crazygames.com/en_US/merge-arena/index.html" },
    // { "id": 4065, "title": "Daily Crossword", "rating": 4.3, "plays": 66000, "category": "Puzzle", "thumb": "images/Puzzle/DailyCrossword.png", "iframe": "https://www.dailycrossword.com/" },
    // { "id": 4066, "title": "Spellfall", "rating": 4.2, "plays": 45000, "category": "Puzzle", "thumb": "images/Puzzle/Spellfall.png", "iframe": "https://games.crazygames.com/en_US/spellfall/index.html" },
    // { "id": 4067, "title": "Match 3D", "rating": 4.3, "plays": 73000, "category": "Puzzle", "thumb": "images/Puzzle/Match3D.png", "iframe": "https://games.crazygames.com/en_US/match-3d/index.html" },
    // { "id": 4068, "title": "Tangram", "rating": 4.1, "plays": 38000, "category": "Puzzle", "thumb": "images/Puzzle/Tangram.png", "iframe": "https://games.crazygames.com/en_US/tangram/index.html" },
    // { "id": 4069, "title": "Find HQ", "rating": 4.0, "plays": 31000, "category": "Puzzle", "thumb": "images/Puzzle/FindHQ.png", "iframe": "https://games.crazygames.com/en_US/find-hq/index.html" },
    // { "id": 4070, "title": "Monster Sudoku", "rating": 4.2, "plays": 47000, "category": "Puzzle", "thumb": "images/Puzzle/MonsterSudoku.png", "iframe": "https://games.crazygames.com/en_US/monster-sudoku/index.html" },
    // { "id": 4071, "title": "Trivia Crack", "rating": 4.4, "plays": 92000, "category": "Puzzle", "thumb": "images/Puzzle/TriviaCrack.png", "iframe": "https://games.crazygames.com/en_US/trivia-crack/index.html" },
    // { "id": 4073, "title": "Hidden Object Studio", "rating": 4.1, "plays": 40000, "category": "Puzzle", "thumb": "images/Puzzle/HiddenObjectStudio.png", "iframe": "https://games.crazygames.com/en_US/hidden-object-studio/index.html" },
    // { "id": 4074, "title": "Roll the Ball", "rating": 4.3, "plays": 62000, "category": "Puzzle", "thumb": "images/Puzzle/RollTheBall.png", "iframe": "https://games.crazygames.com/en_US/roll-the-ball/index.html" },
    // { "id": 4075, "title": "Sugar Sugar", "rating": 4.2, "plays": 55000, "category": "Puzzle", "thumb": "images/Puzzle/SugarSugar.png", "iframe": "https://www.coolmathgames.com/0-sugar-sugar-3" },
    // { "id": 4076, "title": "Bloxorz", "rating": 4.4, "plays": 81000, "category": "Puzzle", "thumb": "images/Puzzle/Bloxorz.png", "iframe": "https://www.coolmathgames.com/0-bloxorz" },
    // { "id": 4080, "title": "Lucky Dice", "rating": 4.0, "plays": 28000, "category": "Puzzle", "thumb": "images/Puzzle/LuckyDice.png", "iframe": "https://games.crazygames.com/en_US/lucky-dice/index.html" },
    // { "id": 4001, "title": "2048", "rating": 4.6, "plays": 180000, "category": "Puzzle", "thumb": "images/Puzzle/2048.png", "iframe": "https://play2048.co/" },
    // { "id": 4011, "title": "Cut the Rope", "rating": 4.6, "plays": 112000, "category": "Puzzle", "thumb": "images/Puzzle/CutTheRope.png", "iframe": "https://www.cuttherope.net/" },
    // { "id": 4013, "title": "Jigsaw Puzzle", "rating": 4.4, "plays": 98000, "category": "Puzzle", "thumb": "images/Puzzle/JigsawPuzzle.png", "iframe": "https://www.jigsawplanet.com/" },
    // { "id": 4015, "title": "Candy Crush", "rating": 4.5, "plays": 175000, "category": "Puzzle", "thumb": "images/Puzzle/CandyCrush.png", "iframe": "https://games.crazygames.com/en_US/candy-crush-soda-saga/index.html" },
    // { "id": 4022, "title": "Unblock Me", "rating": 4.3, "plays": 69000, "category": "Puzzle", "thumb": "images/Puzzle/UnblockMe.png", "iframe": "https://games.crazygames.com/en_US/unblock-me/index.html" },
    // { "id": 4023, "title": "Brain Test", "rating": 4.5, "plays": 107000, "category": "Puzzle", "thumb": "images/Puzzle/BrainTest.png", "iframe": "https://games.crazygames.com/en_US/brain-test-tricky-puzzles/index.html" },
    // { "id": 4024, "title": "Blockudoku", "rating": 4.4, "plays": 83000, "category": "Puzzle", "thumb": "images/Puzzle/Blockudoku.png", "iframe": "https://games.crazygames.com/en_US/blockudoku/index.html" },
    // { "id": 4025, "title": "Nonogram", "rating": 4.3, "plays": 58000, "category": "Puzzle", "thumb": "images/Puzzle/Nonogram.png", "iframe": "https://games.crazygames.com/en_US/nonogram-com/index.html" },
    // { "id": 4026, "title": "Jewel Blast", "rating": 4.2, "plays": 64000, "category": "Puzzle", "thumb": "images/Puzzle/JewelBlast.png", "iframe": "https://games.crazygames.com/en_US/jewel-blast/index.html" },
    // { "id": 4027, "title": "Zuma Deluxe", "rating": 4.4, "plays": 91000, "category": "Puzzle", "thumb": "images/Puzzle/ZumaDeluxe.png", "iframe": "https://games.crazygames.com/en_US/zuma-deluxe/index.html" },
    // { "id": 4028, "title": "Sliding Puzzle", "rating": 4.0, "plays": 41000, "category": "Puzzle", "thumb": "images/Puzzle/SlidingPuzzle.png", "iframe": "https://games.crazygames.com/en_US/sliding-puzzle/index.html" },
    // { "id": 4029, "title": "Color Road", "rating": 4.3, "plays": 72000, "category": "Puzzle", "thumb": "images/Puzzle/ColorRoad.png", "iframe": "https://games.crazygames.com/en_US/color-road/index.html" },
    // { "id": 4020, "title": "Flow Free", "rating": 4.4, "plays": 88000, "category": "Puzzle", "thumb": "images/Puzzle/FlowFree.png", "iframe": "https://games.crazygames.com/en_US/flow-free/index.html" },
    // { "id": 4031, "title": "Stack Ball", "rating": 4.3, "plays": 79000, "category": "Puzzle", "thumb": "images/Puzzle/StackBall.png", "iframe": "https://games.crazygames.com/en_US/stack-ball/index.html" },
    // { "id": 4032, "title": "Water Sort Puzzle", "rating": 4.5, "plays": 103000, "category": "Puzzle", "thumb": "images/Puzzle/WaterSort.png", "iframe": "https://games.crazygames.com/en_US/water-sort-puzzle/index.html" },
    // { "id": 4033, "title": "Ball Sort Puzzle", "rating": 4.4, "plays": 96000, "category": "Puzzle", "thumb": "images/Puzzle/BallSort.png", "iframe": "https://games.crazygames.com/en_US/ball-sort-puzzle/index.html" },
    // { "id": 4034, "title": "Dop 2", "rating": 4.3, "plays": 82000, "category": "Puzzle", "thumb": "images/Puzzle/Dop2.png", "iframe": "https://games.crazygames.com/en_US/dop-2-delete-one-part/index.html" },
    // { "id": 4035, "title": "Rescue Cut", "rating": 4.2, "plays": 67000, "category": "Puzzle", "thumb": "images/Puzzle/RescueCut.png", "iframe": "https://games.crazygames.com/en_US/rescue-cut/index.html" },
    // { "id": 4036, "title": "Stump Me", "rating": 4.1, "plays": 53000, "category": "Puzzle", "thumb": "images/Puzzle/StumpMe.png", "iframe": "https://games.crazygames.com/en_US/stump-me/index.html" },
    // { "id": 4037, "title": "Puzzles and Chaos", "rating": 4.2, "plays": 48000, "category": "Puzzle", "thumb": "images/Puzzle/PuzzlesChaos.png", "iframe": "https://games.crazygames.com/en_US/puzzles-and-chaos/index.html" },
    // { "id": 4038, "title": "Connected Dots", "rating": 4.1, "plays": 37000, "category": "Puzzle", "thumb": "images/Puzzle/ConnectedDots.png", "iframe": "https://games.crazygames.com/en_US/connected-dots/index.html" },
    // { "id": 4039, "title": "Hoop Stars", "rating": 4.2, "plays": 61000, "category": "Puzzle", "thumb": "images/Puzzle/HoopStars.png", "iframe": "https://games.crazygames.com/en_US/hoop-stars/index.html" },
    // { "id": 4040, "title": "Tiny Fishing", "rating": 4.4, "plays": 89000, "category": "Puzzle", "thumb": "images/Puzzle/TinyFishing.png", "iframe": "https://www.coolmathgames.com/0-tiny-fishing" },
    // { "id": 4041, "title": "Snake", "rating": 4.3, "plays": 99000, "category": "Puzzle", "thumb": "images/Puzzle/Snake.png", "iframe": "https://www.coolmathgames.com/0-snake" },
    // { "id": 4042, "title": "Papa's Freezeria", "rating": 4.4, "plays": 94000, "category": "Puzzle", "thumb": "images/Puzzle/PapasFreezeriaTo.png", "iframe": "https://www.coolmathgames.com/0-papas-freezeria" },
    // { "id": 4043, "title": "Number Merge 2048", "rating": 4.3, "plays": 71000, "category": "Puzzle", "thumb": "images/Puzzle/NumberMerge.png", "iframe": "https://games.crazygames.com/en_US/number-merge-2048/index.html" },
    // { "id": 4044, "title": "Toon Blast", "rating": 4.4, "plays": 87000, "category": "Puzzle", "thumb": "images/Puzzle/ToonBlast.png", "iframe": "https://games.crazygames.com/en_US/toon-blast/index.html" },
    // { "id": 4045, "title": "Onet Paradise", "rating": 4.1, "plays": 44000, "category": "Puzzle", "thumb": "images/Puzzle/OnetParadise.png", "iframe": "https://games.crazygames.com/en_US/onet-paradise/index.html" },
    // { "id": 4047, "title": "1010 Block Puzzle", "rating": 4.4, "plays": 76000, "category": "Puzzle", "thumb": "images/Puzzle/1010Block.png", "iframe": "https://games.crazygames.com/en_US/1010-block-puzzle/index.html" },
    // { "id": 4048, "title": "Jewels Blitz", "rating": 4.2, "plays": 58000, "category": "Puzzle", "thumb": "images/Puzzle/JewelsBlitz.png", "iframe": "https://games.crazygames.com/en_US/jewels-blitz/index.html" },
    // { "id": 4049, "title": "Mahjongg Dimensions", "rating": 4.3, "plays": 65000, "category": "Puzzle", "thumb": "images/Puzzle/MahjonggDimensions.png", "iframe": "https://games.crazygames.com/en_US/mahjongg-dimensions/index.html" },
    // { "id": 4052, "title": "Poly Art", "rating": 4.2, "plays": 49000, "category": "Puzzle", "thumb": "images/Puzzle/PolyArt.png", "iframe": "https://games.crazygames.com/en_US/poly-art/index.html" },
    // { "id": 4053, "title": "Klocki", "rating": 4.3, "plays": 41000, "category": "Puzzle", "thumb": "images/Puzzle/Klocki.png", "iframe": "https://games.crazygames.com/en_US/klocki/index.html" },
    // { "id": 4054, "title": "Lines Puzzle", "rating": 4.1, "plays": 36000, "category": "Puzzle", "thumb": "images/Puzzle/LinesPuzzle.png", "iframe": "https://games.crazygames.com/en_US/lines-puzzle/index.html" },
    // { "id": 4055, "title": "Pair Up 3D", "rating": 4.2, "plays": 54000, "category": "Puzzle", "thumb": "images/Puzzle/PairUp3D.png", "iframe": "https://games.crazygames.com/en_US/pair-up-3d/index.html" },
];
