const GAMES_PUZZLE = [
    { "id": 8, "title": "Little Alchemy 2", "rating": 4.8, "plays": 58000, "category": "Puzzle", "thumb": "images/Puzzle/LittleAlchemy2.png", "iframe": "https://littlealchemy2.com/" },
    { "id": 4010, "title": "Solitaire", "rating": 4.6, "plays": 195000, "category": "Puzzle", "thumb": "images/Puzzle/Solitaire.png", "iframe": "https://playpager.com/embed/solitaire/index.html" },
    { "id": 4077, "title": "Lights Off", "rating": 4.0, "plays": 34000, "category": "Puzzle", "thumb": "images/Puzzle/LightsOff.png", "iframe": "https://www.mathsisfun.com/games/lightsout.html" },
    { "id": 4078, "title": "Simon Says", "rating": 4.1, "plays": 43000, "category": "Puzzle", "thumb": "images/Puzzle/SimonSays.png", "iframe": "https://www.mathsisfun.com/games/simon-says.html" },
    { "id": 4079, "title": "Hexanaut.io", "rating": 4.3, "plays": 57000, "category": "Puzzle", "thumb": "images/Puzzle/Hexanaut.png", "iframe": "https://hexanaut.io/" },
    { "id": 4002, "title": "Wordle", "rating": 4.7, "plays": 250000, "category": "Puzzle", "thumb": "images/Puzzle/Wordle.png", "iframe": "https://wordlegame.org/" },
    { "id": 4003, "title": "Sudoku", "rating": 4.5, "plays": 160000, "category": "Puzzle", "thumb": "images/Puzzle/Sudoku.png", "iframe": "https://playpager.com/embed/sudoku/index.html" },
    { "id": 4004, "title": "Chess", "rating": 4.8, "plays": 210000, "category": "Puzzle", "thumb": "images/Puzzle/Chess.png", "iframe": "https://playpager.com/embed/chess/index.html" },
    { "id": 4005, "title": "Mahjong", "rating": 4.5, "plays": 130000, "category": "Puzzle", "thumb": "images/Puzzle/Mahjong.png", "iframe": "https://www.mahjong.io/" },
    { "id": 4006, "title": "Checkers", "rating": 4.3, "plays": 85000, "category": "Puzzle", "thumb": "images/Puzzle/Checkers.png", "iframe": "https://playpager.com/embed/checkers/index.html" },
    { "id": 4007, "title": "Reversi Othello", "rating": 4.2, "plays": 56000, "category": "Puzzle", "thumb": "images/Puzzle/Reversi.png", "iframe": "https://playpager.com/embed/reversi/index.html" },
    { "id": 4008, "title": "Falling Cubes", "rating": 4.1, "plays": 47000, "category": "Puzzle", "thumb": "images/Puzzle/FallingCubes.png", "iframe": "https://playpager.com/embed/cubes/index.html" },
    { "id": 4009, "title": "Word Puzzle", "rating": 4.2, "plays": 63000, "category": "Puzzle", "thumb": "images/Puzzle/WordPuzzle.png", "iframe": "https://playpager.com/embed/wordpuzzle/index.html" },
    { "id": 4012, "title": "Tetris", "rating": 4.7, "plays": 230000, "category": "Puzzle", "thumb": "images/Puzzle/Tetris.png", "iframe": "https://tetris.com/play-tetris" },
    { "id": 4014, "title": "Bubble Shooter", "rating": 4.5, "plays": 148000, "category": "Puzzle", "thumb": "images/Puzzle/BubbleShooter.png", "iframe": "https://www.bubbleshooter.net/" },
    { "id": 4016, "title": "Domino Tiler", "rating": 4.0, "plays": 32000, "category": "Puzzle", "thumb": "images/Puzzle/DominoTiler.png", "iframe": "https://idev.games/embed/domino-tiler" },
    { "id": 4017, "title": "Arcanoid Aquarium", "rating": 4.1, "plays": 38000, "category": "Puzzle", "thumb": "images/Puzzle/ArcanoidAquarium.png", "iframe": "https://idev.games/embed/arcanoid-acuarium" },
    { "id": 4018, "title": "Tower of Hanoi", "rating": 4.2, "plays": 44000, "category": "Puzzle", "thumb": "images/Puzzle/TowerOfHanoi.png", "iframe": "https://www.mathsisfun.com/games/towerofhanoi.html" },
    { "id": 4019, "title": "Minesweeper", "rating": 4.4, "plays": 122000, "category": "Puzzle", "thumb": "images/Puzzle/Minesweeper.png", "iframe": "https://minesweeper.online/" },
    { "id": 4021, "title": "Merge Fruits", "rating": 4.3, "plays": 76000, "category": "Puzzle", "thumb": "images/Puzzle/MergeFruits.png", "iframe": "https://games.crazygames.com/en_US/merge-fruits/index.html" },
    { "id": 4030, "title": "Helix Jump", "rating": 4.5, "plays": 115000, "category": "Puzzle", "thumb": "images/Puzzle/HelixJump.png", "iframe": "https://games.crazygames.com/en_US/helix-jump/index.html" },
    { "id": 4050, "title": "Crossword Puzzle", "rating": 4.4, "plays": 80000, "category": "Puzzle", "thumb": "images/Puzzle/CrosswordPuzzle.png", "iframe": "https://www.crosswordpuzzles.com/" },
    { "id": 4051, "title": "Good Sudoku", "rating": 4.5, "plays": 93000, "category": "Puzzle", "thumb": "images/Puzzle/GoodSudoku.png", "iframe": "https://www.websudoku.com/" },
    { "id": 4046, "title": "Picross", "rating": 4.3, "plays": 52000, "category": "Puzzle", "thumb": "images/Puzzle/Picross.png", "iframe": "https://www.puzzle-nonograms.com/" },
    { "id": 4056, "title": "Emoji Puzzle", "rating": 4.3, "plays": 68000, "category": "Puzzle", "thumb": "images/Puzzle/EmojiPuzzle.png", "iframe": "https://games.crazygames.com/en_US/emoji-puzzle/index.html" },
    { "id": 4057, "title": "Quordle", "rating": 4.4, "plays": 77000, "category": "Puzzle", "thumb": "images/Puzzle/Quordle.png", "iframe": "https://quordle.com/" },
    { "id": 4064, "title": "Numberle", "rating": 4.2, "plays": 51000, "category": "Puzzle", "thumb": "images/Puzzle/Numberle.png", "iframe": "https://numberle.org/" },
    { "id": 4072, "title": "Words of Wonders", "rating": 4.3, "plays": 69000, "category": "Puzzle", "thumb": "images/Puzzle/WordsOfWonders.png", "iframe": "https://games.crazygames.com/en_US/words-of-wonders/index.html" },

];
