const GAMES_ARCADE_1 = [
    { id: 1001, title: "Dune Tiny Wings", rating: 4.4, plays: 12024, category: "Arcade", thumb: "images/Arcade/1/DuneTinyWings.png", iframe: "https://www.madkidgames.com/full/dune-tiny-wings" },
    { id: 1002, title: "Smashy Road: Wanted", rating: 4.5, plays: 34200, category: "Arcade", thumb: "images/Arcade/1/SmashyRoadWanted.png", iframe: "https://www.madkidgames.com/full/smashy-road-wanted" },
    { id: 1003, title: "Crossy Road Castle", rating: 4.6, plays: 28500, category: "Arcade", thumb: "images/Arcade/1/CrossyRoadCastle.png", iframe: "https://www.madkidgames.com/full/crossy-road-castle" },
    { id: 1004, title: "Subway Princess Runner", rating: 4.3, plays: 41000, category: "Arcade", thumb: "images/Arcade/1/SubwayPrincessRunner.png", iframe: "https://www.madkidgames.com/full/subway-princess-runner" },
    { id: 1005, title: "Jetpack Joyride", rating: 4.7, plays: 55000, category: "Arcade", thumb: "images/Arcade/1/JetpackJoyride.png", iframe: "https://www.madkidgames.com/full/jetpack-joyride" },
    { id: 1006, title: "Temple Run 2", rating: 4.8, plays: 88000, category: "Arcade", thumb: "images/Arcade/1/TempleRun2.png", iframe: "https://www.madkidgames.com/full/temple-run-2" },
    { id: 1007, title: "Minion Rush", rating: 4.5, plays: 62000, category: "Arcade", thumb: "images/Arcade/1/MinionRush.png", iframe: "https://www.madkidgames.com/full/minion-rush" },
    { id: 1008, title: "Stunt Bike Extreme", rating: 5.0, plays: 5657, category: "Arcade", thumb: "images/Arcade/1/StuntBikeExtreme.png", iframe: "https://www.madkidgames.com/full/stunt-bike-extreme" },
    { id: 1009, title: "Hill Climb Racing", rating: 4.7, plays: 120000, category: "Arcade", thumb: "images/Arcade/1/HillClimbRacing.png", iframe: "https://www.madkidgames.com/full/hill-climb-racing" },
    { id: 1010, title: "Turbo Dismount", rating: 4.4, plays: 23000, category: "Arcade", thumb: "images/Arcade/1/TurboDismount.png", iframe: "https://www.madkidgames.com/full/turbo-dismount" },
    { id: 1011, title: "Knife Hit", rating: 4.3, plays: 31000, category: "Arcade", thumb: "images/Arcade/1/KnifeHit.png", iframe: "https://www.madkidgames.com/full/knife-hit" },
    { id: 1012, title: "Ball Blast", rating: 4.2, plays: 19500, category: "Arcade", thumb: "images/Arcade/1/BallBlast.png", iframe: "https://www.madkidgames.com/full/ball-blast" },
    { id: 1013, title: "Helix Jump", rating: 4.5, plays: 47000, category: "Arcade", thumb: "images/Arcade/1/HelixJump.png", iframe: "https://www.madkidgames.com/full/helix-jump" },
    { id: 1014, title: "Stack Ball", rating: 4.3, plays: 28000, category: "Arcade", thumb: "images/Arcade/1/StackBall.png", iframe: "https://www.madkidgames.com/full/stack-ball" },
    { id: 1015, title: "Flip Bottle", rating: 4.1, plays: 15000, category: "Arcade", thumb: "images/Arcade/1/FlipBottle.png", iframe: "https://www.madkidgames.com/full/flip-bottle" },
    { id: 1016, title: "Brain Dots", rating: 4.4, plays: 21000, category: "Arcade", thumb: "images/Arcade/1/BrainDots.png", iframe: "https://www.madkidgames.com/full/brain-dots" },
    { id: 1017, title: "Color Switch", rating: 4.3, plays: 39000, category: "Arcade", thumb: "images/Arcade/1/ColorSwitch.png", iframe: "https://www.madkidgames.com/full/color-switch" },
    { id: 1018, title: "Super Smash Flash 2", rating: 4.8, plays: 93000, category: "Arcade", thumb: "images/Arcade/1/SuperSmashFlash2.png", iframe: "https://www.madkidgames.com/full/super-smash-flash-2" },
    { id: 1019, title: "Granny", rating: 4.6, plays: 4669, category: "Arcade", thumb: "images/Arcade/1/Granny.png", iframe: "https://www.madkidgames.com/full/granny" },
    { id: 1020, title: "Bike Race Pro", rating: 4.4, plays: 17800, category: "Arcade", thumb: "images/Arcade/1/BikeRacePro.png", iframe: "https://www.madkidgames.com/full/bike-race-pro" },
    { id: 1021, title: "Road Rush Cars", rating: 4.2, plays: 12300, category: "Arcade", thumb: "images/Arcade/1/RoadRushCars.png", iframe: "https://www.madkidgames.com/full/road-rush-cars" },
    { id: 1022, title: "Sky Roller", rating: 4.5, plays: 34000, category: "Arcade", thumb: "images/Arcade/1/SkyRoller.png", iframe: "https://www.madkidgames.com/full/sky-roller" },
    { id: 1023, title: "Bounce Ball", rating: 4.1, plays: 9800, category: "Arcade", thumb: "images/Arcade/1/BounceBall.png", iframe: "https://www.madkidgames.com/full/bounce-ball" },
    { id: 1024, title: "Smash Hit", rating: 4.6, plays: 58000, category: "Arcade", thumb: "images/Arcade/1/SmashHit.png", iframe: "https://www.madkidgames.com/full/smash-hit" },
    { id: 1025, title: "Piano Tiles 2", rating: 4.7, plays: 74000, category: "Arcade", thumb: "images/Arcade/1/PianoTiles2.png", iframe: "https://www.madkidgames.com/full/piano-tiles-2" },
    { id: 1026, title: "Talking Tom Gold Run", rating: 4.5, plays: 49000, category: "Arcade", thumb: "images/Arcade/1/TalkingTomGoldRun.png", iframe: "https://www.madkidgames.com/full/talking-tom-gold-run" },
    { id: 1027, title: "Flip Master", rating: 4.4, plays: 22000, category: "Arcade", thumb: "images/Arcade/1/FlipMaster.png", iframe: "https://www.madkidgames.com/full/flip-master" },
    { id: 1028, title: "Toilet Rush", rating: 4.0, plays: 8700, category: "Arcade", thumb: "images/Arcade/1/ToiletRush.png", iframe: "https://www.madkidgames.com/full/toilet-rush" },
    { id: 1029, title: "Zombie Tsunami", rating: 4.6, plays: 67000, category: "Arcade", thumb: "images/Arcade/1/ZombieTsunami.png", iframe: "https://www.madkidgames.com/full/zombie-tsunami" },
    { id: 1030, title: "Candy Crush Saga", rating: 4.8, plays: 210000, category: "Arcade", thumb: "images/Arcade/1/CandyCrushSaga.png", iframe: "https://www.madkidgames.com/full/candy-crush-saga" },
    { id: 1031, title: "Angry Gran Run", rating: 4.3, plays: 31000, category: "Arcade", thumb: "images/Arcade/1/AngryGranRun.png", iframe: "https://www.madkidgames.com/full/angry-gran-run" },
    { id: 1032, title: "Nyan Cat: Lost In Space", rating: 4.2, plays: 18000, category: "Arcade", thumb: "images/Arcade/1/NyanCatLostInSpace.png", iframe: "https://www.madkidgames.com/full/nyan-cat-lost-in-space" },
    { id: 1033, title: "Slope", rating: 4.7, plays: 98000, category: "Arcade", thumb: "images/Arcade/1/Slope.png", iframe: "https://www.madkidgames.com/full/slope" },
    { id: 1034, title: "Basketball Stars", rating: 4.5, plays: 54000, category: "Arcade", thumb: "images/Arcade/1/BasketballStars.png", iframe: "https://www.madkidgames.com/full/basketball-stars" },
    { id: 1035, title: "Bubble Shooter", rating: 4.4, plays: 43000, category: "Arcade", thumb: "images/Arcade/1/BubbleShooter.png", iframe: "https://www.madkidgames.com/full/bubble-shooter" },
    { id: 1036, title: "Burnin' Rubber 5 HD", rating: 4.6, plays: 37000, category: "Arcade", thumb: "images/Arcade/1/BurninRubber5HD.png", iframe: "https://www.madkidgames.com/full/burnin-rubber-5-hd" },
    { id: 1037, title: "Moto X3M Bike Race", rating: 4.7, plays: 82000, category: "Arcade", thumb: "images/Arcade/1/MotoX3MBikeRace.png", iframe: "https://www.madkidgames.com/full/moto-x3m-bike-race" },
    { id: 1038, title: "Punch Bob", rating: 4.2, plays: 11500, category: "Arcade", thumb: "images/Arcade/1/PunchBob.png", iframe: "https://www.madkidgames.com/full/punch-bob" },
    { id: 1039, title: "Fireboy and Watergirl", rating: 4.8, plays: 105000, category: "Arcade", thumb: "images/Arcade/1/FireboyAndWatergirl.png", iframe: "https://www.madkidgames.com/full/fireboy-and-watergirl" },
    { id: 1040, title: "Hole.io", rating: 4.5, plays: 76000, category: "Arcade", thumb: "images/Arcade/1/Holeio.png", iframe: "https://www.madkidgames.com/full/hole-io" },
];
