const GAMES_ARCADE_2 = [
  { id:1041, title:"Bowmasters",                   rating:4.5, plays:61000,  category:"Arcade", thumb:"images/Arcade/2/Bowmasters.png",              iframe:"https://www.madkidgames.com/full/bowmasters" },
  { id:1042, title:"Angry Birds Reloaded",         rating:4.6, plays:47000,  category:"Arcade", thumb:"images/Arcade/2/AngryBirdsReloaded.png",      iframe:"https://www.madkidgames.com/full/angry-birds-reloaded" },
  { id:1043, title:"Ragdoll Archers",              rating:4.4, plays:28000,  category:"Arcade", thumb:"images/Arcade/2/RagdollArchers.png",           iframe:"https://www.madkidgames.com/full/ragdoll-archers" },
  { id:1044, title:"Stickman Warrior",             rating:4.3, plays:19000,  category:"Arcade", thumb:"images/Arcade/2/StickmanWarrior.png",         iframe:"https://www.madkidgames.com/full/stickman-warrior" },
  { id:1045, title:"Sniper 3D",                    rating:4.5, plays:52000,  category:"Arcade", thumb:"images/Arcade/2/Sniper3D.png",                iframe:"https://www.madkidgames.com/full/sniper-3d" },
  { id:1046, title:"Agent Action",                 rating:4.4, plays:33000,  category:"Arcade", thumb:"images/Arcade/2/AgentAction.png",             iframe:"https://www.madkidgames.com/full/agent-action" },
  { id:1047, title:"Gangstar Vegas",               rating:4.6, plays:68000,  category:"Arcade", thumb:"images/Arcade/2/GangstarVegas.png",           iframe:"https://www.madkidgames.com/full/gangstar-vegas" },
  { id:1048, title:"Stickman World Battle",        rating:5.0, plays:5749,   category:"Arcade", thumb:"images/Arcade/2/StickmanWorldBattle.png",     iframe:"https://www.madkidgames.com/full/stickman-world-battle" },
  { id:1049, title:"Mad Skills BMX 2",             rating:4.5, plays:24000,  category:"Arcade", thumb:"images/Arcade/2/MadSkillsBMX2.png",           iframe:"https://www.madkidgames.com/full/mad-skills-bmx-2" },
  { id:1050, title:"Drift Ride",                   rating:4.3, plays:17200,  category:"Arcade", thumb:"images/Arcade/2/DriftRide.png",               iframe:"https://www.madkidgames.com/full/drift-ride" },
  { id:1051, title:"Geometry Dash Meltdown",       rating:4.6, plays:59000,  category:"Arcade", thumb:"images/Arcade/2/GeometryDashMeltdown.png",   iframe:"https://www.madkidgames.com/full/geometry-dash-meltdown" },
  { id:1052, title:"Shadow Fight 2",               rating:4.8, plays:112000, category:"Arcade", thumb:"images/Arcade/2/ShadowFight2.png",            iframe:"https://www.madkidgames.com/full/shadow-fight-2" },
  { id:1053, title:"Mortal Kombat",                rating:4.7, plays:88000,  category:"Arcade", thumb:"images/Arcade/2/MortalKombat.png",            iframe:"https://www.madkidgames.com/full/mortal-kombat" },
  { id:1054, title:"Street Fighter",               rating:4.7, plays:73000,  category:"Arcade", thumb:"images/Arcade/2/StreetFighter.png",           iframe:"https://www.madkidgames.com/full/street-fighter" },
  { id:1055, title:"Egg Inc",                      rating:4.5, plays:41000,  category:"Arcade", thumb:"images/Arcade/2/EggInc.png",                  iframe:"https://www.madkidgames.com/full/egg-inc" },
  { id:1056, title:"Flappy Dunk",                  rating:4.2, plays:16500,  category:"Arcade", thumb:"images/Arcade/2/FlappyDunk.png",              iframe:"https://www.madkidgames.com/full/flappy-dunk" },
  { id:1057, title:"Tower Bloxx",                  rating:4.1, plays:13000,  category:"Arcade", thumb:"images/Arcade/2/TowerBloxx.png",              iframe:"https://www.madkidgames.com/full/tower-bloxx" },
  { id:1058, title:"Space Frontier",               rating:4.4, plays:29000,  category:"Arcade", thumb:"images/Arcade/2/SpaceFrontier.png",           iframe:"https://www.madkidgames.com/full/space-frontier" },
  { id:1059, title:"Johnny Trigger",               rating:4.5, plays:38000,  category:"Arcade", thumb:"images/Arcade/2/JohnnyTrigger.png",           iframe:"https://www.madkidgames.com/full/johnny-trigger" },
  { id:1060, title:"Sky Dancer",                   rating:4.3, plays:22000,  category:"Arcade", thumb:"images/Arcade/2/SkyDancer.png",               iframe:"https://www.madkidgames.com/full/sky-dancer" },
  { id:1061, title:"Aquapark.io",                  rating:4.5, plays:54000,  category:"Arcade", thumb:"images/Arcade/2/Aquaparkio.png",              iframe:"https://www.madkidgames.com/full/aquapark-io" },
  { id:1062, title:"Archery King",                 rating:4.4, plays:32000,  category:"Arcade", thumb:"images/Arcade/2/ArcheryKing.png",             iframe:"https://www.madkidgames.com/full/archery-king" },
  { id:1063, title:"Toon Blast",                   rating:4.6, plays:66000,  category:"Arcade", thumb:"images/Arcade/2/ToonBlast.png",               iframe:"https://www.madkidgames.com/full/toon-blast" },
  { id:1064, title:"Toy Blast",                    rating:4.5, plays:48000,  category:"Arcade", thumb:"images/Arcade/2/ToyBlast.png",                iframe:"https://www.madkidgames.com/full/toy-blast" },
  { id:1065, title:"Candy Crush Jelly",            rating:4.4, plays:39000,  category:"Arcade", thumb:"images/Arcade/2/CandyCrushJelly.png",         iframe:"https://www.madkidgames.com/full/candy-crush-jelly" },
  { id:1066, title:"Dragon City Mobile",           rating:4.6, plays:71000,  category:"Arcade", thumb:"images/Arcade/2/DragonCityMobile.png",        iframe:"https://www.madkidgames.com/full/dragon-city-mobile" },
  { id:1067, title:"Pou",                          rating:4.3, plays:27000,  category:"Arcade", thumb:"images/Arcade/2/Pou.png",                     iframe:"https://www.madkidgames.com/full/pou" },
  { id:1068, title:"Tom and Jerry Mouse Maze",     rating:4.2, plays:15000,  category:"Arcade", thumb:"images/Arcade/2/TomAndJerryMouseMaze.png",    iframe:"https://www.madkidgames.com/full/tom-and-jerry-mouse-maze" },
  { id:1069, title:"Subway Surfers Paris",         rating:4.7, plays:83000,  category:"Arcade", thumb:"images/Arcade/2/SubwaySurfersParis.png",      iframe:"https://www.madkidgames.com/full/subway-surfers-paris" },
  { id:1070, title:"Temple Run Oz",                rating:4.6, plays:44000,  category:"Arcade", thumb:"images/Arcade/2/TempleRunOz.png",             iframe:"https://www.madkidgames.com/full/temple-run-oz" },
  { id:1071, title:"Hopscotch",                    rating:4.0, plays:9800,   category:"Arcade", thumb:"images/Arcade/2/Hopscotch.png",               iframe:"https://www.madkidgames.com/full/hopscotch" },
  { id:1072, title:"Dizzy Dino Jump",              rating:4.1, plays:11200,  category:"Arcade", thumb:"images/Arcade/2/DizzyDinoJump.png",           iframe:"https://www.madkidgames.com/full/dizzy-dino-jump" },
  { id:1073, title:"Red Ball 4",                   rating:4.5, plays:57000,  category:"Arcade", thumb:"images/Arcade/2/RedBall4.png",                iframe:"https://www.madkidgames.com/full/red-ball-4" },
  { id:1074, title:"Donkey Kong",                  rating:4.7, plays:91000,  category:"Arcade", thumb:"images/Arcade/2/DonkeyKong.png",              iframe:"https://www.madkidgames.com/full/donkey-kong" },
  { id:1075, title:"Super Mario Bros",             rating:4.9, plays:175000, category:"Arcade", thumb:"images/Arcade/2/SuperMarioBros.png",          iframe:"https://www.madkidgames.com/full/super-mario-bros" },
  { id:1076, title:"Asteroids",                    rating:4.2, plays:18500,  category:"Arcade", thumb:"images/Arcade/2/Asteroids.png",               iframe:"https://www.madkidgames.com/full/asteroids" },
  { id:1077, title:"Galaga",                       rating:4.4, plays:24000,  category:"Arcade", thumb:"images/Arcade/2/Galaga.png",                  iframe:"https://www.madkidgames.com/full/galaga" },
  { id:1078, title:"Centipede",                    rating:4.1, plays:13500,  category:"Arcade", thumb:"images/Arcade/2/Centipede.png",               iframe:"https://www.madkidgames.com/full/centipede" },
  { id:1079, title:"Frogger",                      rating:4.3, plays:22500,  category:"Arcade", thumb:"images/Arcade/2/Frogger.png",                 iframe:"https://www.madkidgames.com/full/frogger" },
  { id:1080, title:"Q*bert",                       rating:4.0, plays:9500,   category:"Arcade", thumb:"images/Arcade/2/Qbert.png",                   iframe:"https://www.madkidgames.com/full/qbert" },
];
