const GAMES_ACTION = [
    { "id": 1002, "title": "Gartic.io", "rating": 4.2, "plays": 60000, "category": "Action", "thumb": "images/Action/Gartic.png", "iframe": "https://gartic.io/" },
    { "id": 1003, "title": "Lordz2.io", "rating": 4.2, "plays": 34000, "category": "Action", "thumb": "images/Action/Lordz2.png", "iframe": "https://www.lordz2.io/" },
    { "id": 1004, "title": "Dead Zed", "rating": 4.1, "plays": 43000, "category": "Action", "thumb": "images/Action/DeadZed.png", "iframe": "https://games.crazygames.com/en_US/dead-zed/index.html" },
    { "id": 1005, "title": "Shell Shockers", "rating": 4.5, "plays": 87000, "category": "Action", "thumb": "images/Action/ShellShockers.png", "iframe": "https://shellshock.io/" },
    { "id": 1006, "title": "Krunker.io", "rating": 4.7, "plays": 120000, "category": "Action", "thumb": "images/Action/Krunker.png", "iframe": "https://krunker.io/" },
    { "id": 1007, "title": "Moomoo.io", "rating": 4.2, "plays": 62000, "category": "Action", "thumb": "images/Action/Moomoo.png", "iframe": "https://moomoo.io/" },
    { "id": 1008, "title": "Surviv.io", "rating": 4.4, "plays": 75000, "category": "Action", "thumb": "images/Action/Surviv.png", "iframe": "https://survev.io/" },
    { "id": 1009, "title": "Diep.io", "rating": 4.3, "plays": 68000, "category": "Action", "thumb": "images/Action/Diep.png", "iframe": "https://diep.io/" },
    { "id": 1010, "title": "Zombs Royale", "rating": 4.5, "plays": 88000, "category": "Action", "thumb": "images/Action/ZombsRoyale.png", "iframe": "https://zombsroyale.io/" },
    { "id": 1011, "title": "Warbrokers.io", "rating": 4.3, "plays": 45000, "category": "Action", "thumb": "images/Action/Warbrokers.png", "iframe": "https://warbrokers.io/" },
    { "id": 1012, "title": "Paper.io 2", "rating": 4.4, "plays": 92000, "category": "Action", "thumb": "images/Action/PaperIO2.png", "iframe": "https://paper-io.com/" },
    { "id": 1013, "title": "Gunblood", "rating": 4.2, "plays": 55000, "category": "Action", "thumb": "images/Action/Gunblood.png", "iframe": "https://games.crazygames.com/en_US/gunblood/index.html" },
    { "id": 1014, "title": "Pixel Warfare", "rating": 4.2, "plays": 48000, "category": "Action", "thumb": "images/Action/PixelWarfare.png", "iframe": "https://games.crazygames.com/en_US/pixel-warfare/index.html" },
    { "id": 1015, "title": "Lordz.io", "rating": 4.2, "plays": 36000, "category": "Action", "thumb": "images/Action/Lordz.png", "iframe": "https://www.lordz.io/" },
    { "id": 1016, "title": "Wings.io", "rating": 4.3, "plays": 54000, "category": "Action", "thumb": "images/Action/Wings.png", "iframe": "https://wings.io/" },
    { "id": 1017, "title": "Stabfish.io", "rating": 4.0, "plays": 31000, "category": "Action", "thumb": "images/Action/Stabfish.png", "iframe": "https://stabfish.io/" },
    { "id": 1018, "title": "Venge.io", "rating": 4.5, "plays": 71000, "category": "Action", "thumb": "images/Action/Venge.png", "iframe": "https://venge.io/" },
    { "id": 1019, "title": "Bruh.io", "rating": 4.1, "plays": 28000, "category": "Action", "thumb": "images/Action/Bruh.png", "iframe": "https://bruh.io/" },
    { "id": 1020, "title": "Worms Zone", "rating": 4.4, "plays": 85000, "category": "Action", "thumb": "images/Action/WormsZone.png", "iframe": "https://wormszone.io/" },
    { "id": 1021, "title" :"Tank Trouble","rating":4.3, "plays" :34000,  "category":"Action",        "thumb":"images/Action/TankTrouble.png",                  "iframe":"https://tanktrouble.com/" },
    { "id": 1022, "title": "Sploop.io", "rating": 4.1, "plays": 31000, "category": "Action", "thumb": "images/Action/Sploop.png", "iframe": "https://sploop.io/" },
    { "id": 1023, "title": "Vampire Land", "rating": 4.0, "plays": 25000, "category": "Action", "thumb": "images/Action/VampireLand.png", "iframe": "https://idev.games/embed/vampire-land" },
    { "id": 1024, "title": "Zombie Tower Defense", "rating": 4.2, "plays": 44000, "category": "Action", "thumb": "images/Action/ZombieTD.png", "iframe": "https://idev.games/embed/zombie-tower-defense-z-sector" },
    { "id": 1025, "title": "Horrible Platformer", "rating": 3.8, "plays": 19000, "category": "Action", "thumb": "images/Action/HorriblePlatformer.png", "iframe": "https://idev.games/embed/horrible-platformer" },
    { "id": 1026, "title": "Bonk.io", "rating": 4.3, "plays": 57000, "category": "Action", "thumb": "images/Action/Bonk.png", "iframe": "https://bonk.io/" },
    { "id": 1027, "title": "Defly.io", "rating": 4.2, "plays": 42000, "category": "Action", "thumb": "images/Action/Defly.png", "iframe": "https://defly.io/" },
    { "id": 1028, "title": "Bullet Force", "rating": 4.6, "plays": 95000, "category": "Action", "thumb": "images/Action/BulletForce.png", "iframe": "https://games.crazygames.com/en_US/bullet-force-multiplayer/index.html" },
    { "id": 1029, "title": "Little Big Snake", "rating": 4.4, "plays": 78000, "category": "Action", "thumb": "images/Action/LittleBigSnake.png", "iframe": "https://littlebigsnake.com/" },
    { "id": 1030, "title": "Arras.io", "rating": 4.3, "plays": 49000, "category": "Action", "thumb": "images/Action/Arras.png", "iframe": "https://arras.io/" },
    { "id": 1031, "title": "Shooterz.io", "rating": 4.0, "plays": 26000, "category": "Action", "thumb": "images/Action/Shooterz.png", "iframe": "https://shooterz.io/" },
    { "id": 1032, "title": "Skribbl.io", "rating": 4.5, "plays": 96000, "category": "Action", "thumb": "images/Action/Skribbl.png", "iframe": "https://skribbl.io/" },
    { "id": 1033, "title": "Townscaper", "rating": 4.4, "plays": 63000, "category": "Action", "thumb": "images/Action/Townscaper.png", "iframe": "https://oskarstalberg.com/Townscaper/" },
    { "id": 1034, "title": "Territorial.io", "rating": 4.4, "plays": 69000, "category": "Action", "thumb": "images/Action/Territorial.png", "iframe": "https://territorial.io/" },
    { "id": 1035, "title": "Smash Karts", "rating": 4.6, "plays": 102000, "category": "Action", "thumb": "images/Action/SmashKarts.png", "iframe": "https://smashkarts.io/" },
    { "id": 1036, "title": "Evowars.io", "rating": 4.3, "plays": 55000, "category": "Action", "thumb": "images/Action/Evowars.png", "iframe": "https://evowars.io/" },
    { "id": 1037, "title": "Zombs.io", "rating": 4.2, "plays": 48000, "category": "Action", "thumb": "images/Action/Zombs.png", "iframe": "https://zombs.io/" },
    { "id": 1038, "title": "Gats.io", "rating": 4.1, "plays": 34000, "category": "Action", "thumb": "images/Action/Gats.png", "iframe": "https://gats.io/" },
    { "id": 1039, "title": "Ragdoll Archers", "rating": 4.3, "plays": 61000, "category": "Action", "thumb": "images/Action/RagdollArchers.png", "iframe": "https://games.crazygames.com/en_US/ragdoll-archers/index.html" },
    { "id": 1040, "title": "Draw Climber", "rating": 4.1, "plays": 53000, "category": "Action", "thumb": "images/Action/DrawClimber.png", "iframe": "https://games.crazygames.com/en_US/draw-climber/index.html" },
    { "id": 1041, "title": "Dino Game", "rating": 4.0, "plays": 200000, "category": "Action", "thumb": "images/Action/DinoGame.png", "iframe": "https://chromedino.com/" },
    { "id": 1042, "title": "Slope", "rating": 4.5, "plays": 130000, "category": "Action", "thumb": "images/Action/Slope.png", "iframe": "https://slope-game.com/" },
    { "id": 1043, "title": "Drift Hunters", "rating": 4.6, "plays": 107000, "category": "Action", "thumb": "images/Action/DriftHunters.png", "iframe": "https://games.crazygames.com/en_US/drift-hunters/index.html" },
    { "id": 1044, "title": "Crossy Road", "rating": 4.4, "plays": 99000, "category": "Action", "thumb": "images/Action/CrossyRoad.png", "iframe": "https://crossyroad.com/" },
    { "id": 1045, "title": "Geometry Dash", "rating": 4.5, "plays": 122000, "category": "Action", "thumb": "images/Action/GeometryDash.png", "iframe": "https://geometrydashgame.com/" },
    { "id": 1046, "title": "Bowman", "rating": 4.0, "plays": 39000, "category": "Action", "thumb": "images/Action/Bowman.png", "iframe": "https://games.crazygames.com/en_US/bowman/index.html" },
    { "id": 1047, "title": "Battle for the Galaxy", "rating": 4.2, "plays": 45000, "category": "Action", "thumb": "images/Action/BattleGalaxy.png", "iframe": "https://games.crazygames.com/en_US/battle-for-the-galaxy/index.html" },
    { "id": 1048, "title": "Copter.io", "rating": 4.0, "plays": 30000, "category": "Action", "thumb": "images/Action/Copter.png", "iframe": "https://copter.io/" },
];
