const path = require('path');
const fs = require('fs');

const file = path.join(__dirname, '..', 'js', 'seo-meta.js');
const backup = file + '.bak';

if (!fs.existsSync(file)) {
  console.error('File not found:', file);
  process.exit(2);
}

fs.copyFileSync(file, backup);
console.log('Backup saved to', backup);

const m = require(file);
const { SEO_CATEGORIES, SEO_GAMES } = m;

function hasContent(o) {
  if (!o || typeof o !== 'object') return false;
  for (const k of Object.keys(o)) {
    const v = o[k];
    if (typeof v === 'string' && v.trim() !== '') return true;
    if (typeof v === 'object' && hasContent(v)) return true;
  }
  return false;
}

function findLang(o, lang) {
  if (!o || typeof o !== 'object') return {};
  let cur = o;
  // Try to unwrap repeated lang wrappers
  const maxDepth = 10;
  let depth = 0;
  while (cur && typeof cur === 'object' && depth++ < maxDepth) {
    if (cur[lang] && typeof cur[lang] === 'object' && hasContent(cur[lang])) return cur[lang];
    if (hasContent(cur) && (cur.title || cur.h1 || cur.intro || cur.description || cur.Instructions)) return cur;
    if (cur[lang] && typeof cur[lang] === 'object') { cur = cur[lang]; continue; }
    break;
  }

  // DFS search for a nested object with lang
  let found = null;
  function dfs(node) {
    if (!node || typeof node !== 'object') return false;
    if (node[lang] && typeof node[lang] === 'object' && hasContent(node[lang])) { found = node[lang]; return true; }
    for (const k of Object.keys(node)) {
      if (dfs(node[k])) return true;
    }
    return false;
  }
  dfs(o);
  if (found && hasContent(found)) return found;

  // fallback: if object itself has content, return it
  if (hasContent(o)) return o;
  return {};
}

function normalizeMap(map) {
  const res = {};
  for (const key of Object.keys(map || {})) {
    const val = map[key];
    res[key] = {
      fr: findLang(val, 'fr') || {},
      en: findLang(val, 'en') || {}
    };
  }
  return res;
}

const normCats = normalizeMap(SEO_CATEGORIES || {});
const normGames = normalizeMap(SEO_GAMES || {});

function collapseWrapped(obj) {
  if (!obj || typeof obj !== 'object') return obj;
  const keys = Object.keys(obj);
  if (keys.length === 1 && (keys[0] === 'fr' || keys[0] === 'en') && typeof obj[keys[0]] === 'object') {
    return collapseWrapped(obj[keys[0]]);
  }
  for (const k of keys) {
    if (typeof obj[k] === 'object') obj[k] = collapseWrapped(obj[k]);
  }
  return obj;
}

// Collapse nested same-language wrappers left by merge process
for (const k of Object.keys(normCats)) {
  normCats[k].fr = collapseWrapped(normCats[k].fr) || {};
  normCats[k].en = collapseWrapped(normCats[k].en) || {};
}
for (const k of Object.keys(normGames)) {
  normGames[k].fr = collapseWrapped(normGames[k].fr) || {};
  normGames[k].en = collapseWrapped(normGames[k].en) || {};
}

// Final extraction to ensure each language object contains actual fields
for (const k of Object.keys(normCats)) {
  // Try deeper picks from the original source to avoid nested wrappers
  const origCat = SEO_CATEGORIES[k];
  function deepPickLang(obj, lang) {
    let res = findLang(obj, lang) || {};
    let i = 0;
    while (i++ < 10 && res && typeof res === 'object') {
      const keys = Object.keys(res);
      if (keys.includes('fr') || keys.includes('en')) {
        if (res[lang] && hasContent(res[lang])) { res = res[lang]; continue; }
        const other = lang === 'fr' ? 'en' : 'fr';
        if (res[other] && hasContent(res[other])) { res = res[other]; continue; }
        break;
      }
      break;
    }
    return res || {};
  }

  normCats[k].fr = deepPickLang(origCat, 'fr') || {};
  normCats[k].en = deepPickLang(origCat, 'en') || {};
}
for (const k of Object.keys(normGames)) {
  const origGame = SEO_GAMES[k];
  function deepPickLangGame(obj, lang) {
    let res = findLang(obj, lang) || {};
    let i = 0;
    while (i++ < 10 && res && typeof res === 'object') {
      const keys = Object.keys(res);
      if (keys.includes('fr') || keys.includes('en')) {
        if (res[lang] && hasContent(res[lang])) { res = res[lang]; continue; }
        const other = lang === 'fr' ? 'en' : 'fr';
        if (res[other] && hasContent(res[other])) { res = res[other]; continue; }
        break;
      }
      break;
    }
    return res || {};
  }

  normGames[k].fr = deepPickLangGame(origGame, 'fr') || {};
  normGames[k].en = deepPickLangGame(origGame, 'en') || {};
}

const out = `// Normalized bilingual SEO file\n// Generated by scripts/sanitize-seo.js\n\nconst SEO_CATEGORIES = ${JSON.stringify(normCats, null, 2)};\n\nconst SEO_GAMES = ${JSON.stringify(normGames, null, 2)};\n\nmodule.exports = { SEO_CATEGORIES, SEO_GAMES };\n`;

fs.writeFileSync(file, out, 'utf8');
console.log('Wrote normalized seo to', file);
